### ISSUE TITLE
Failing to retrieve zone info for one zone in Cloudflare account

### ISSUE THREAD

**Issue by FingerlessGlov3s** [StackExchange/dnscontrol#1436]
I'm just in the process of setting up dnscontrol for my cloudflare domains.

It works for all domains but one, which is erroring with the below, but the error doesn't seem to point out the issue. How do I go about looking for the issue? I assume there's something in Cloudflare that's configured that isn't support in dnscontrol. I've added -v to get verbose output but that didn't add any more output.

Any ideas?

```
.\dnscontrol -v get-zone --format=js cloudflare CLOUDFLAREAPI mydomain.pm
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).nativeToRecord(0x0, {0xc00012a108, 0x6}, {{0x1dda74c0, 0xed4ff4281, 0x0}, {0x1dda74c0, 0xed4ff4281, 0x0}, {0xc00012bd30, ...}, ...})
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/cloudflareProvider.go:630 +0x579
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).getRecordsForDomain(0xc000159310, {0xc00003e920, 0x6}, {0xc00012a108, 0x6})
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/rest.go:38 +0x1d3
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).GetZoneRecords(0xc00012a0f0, {0xc00012a108, 0x6})
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/cloudflareProvider.go:117 +0x57
github.com/StackExchange/dnscontrol/v3/commands.GetZone({{{0x21b7e8a, 0xa}}, {0xc00012a0d0, 0xa}, {0xc00012a0f0, 0xd}, {0xc0006ae470, 0x1, 0x1}, {0xc00012a0a9, ...}, ...})
        /home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:183 +0x590
github.com/StackExchange/dnscontrol/v3/commands.glob..func5.1(0xc0006c02c0)
        /home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:30 +0x245
github.com/urfave/cli/v2.(*Command).Run(0xc0003b0480, 0xc0006c00c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000644d00, {0x23dc800, 0xc00012a130}, {0xc000156000, 0x7, 0x8})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc000106360, 0x21b9977})
        /home/runner/work/dnscontrol/dnscontrol/commands/commands.go:65 +0x2a9
main.main()
        /home/runner/work/dnscontrol/dnscontrol/main.go:35 +0x134
```

**Comment by tlimoncelli** [comment]
It's failing on a line of code that is looking for the target on an SRV record.  Is there a chance the target is missing?

**Comment by FingerlessGlov3s** [comment]
Indeed I did!

Thank you for the quick support 😀

**Comment by tlimoncelli** [comment]
Glad to help! You caught me on a slow day :-)

I'm going to re-open this because the code shouldn't crash when that happens.
