### ISSUE TITLE
DNSControl panics, while trying to print corrections on push.

### ISSUE THREAD

**Issue by szczot3k** [StackExchange/dnscontrol#1440]
Hi,
we're using DNSControl in production to control a quite big DNS Zone (about 1400 records).
While trying to move the DNS to Cloudflare, we've encountered a DNSControl panic, while trying to print corrections on push.
It managed to print corrections on preview (https://github.com/itwzhp/infrastruktura/pull/139), but it failed while deploying the zone to Cloudflare - https://github.com/itwzhp/infrastruktura/runs/5422959457. 

We imported the zone manually, before trying to deploy it with dnscontrol, to avoid hitting any API limits. 

I'm attaching a stacktrace below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd2cfc0]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).createRec.func1(0x2339060, 0x0)
	/go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/rest.go:154 +0x1e0
github.com/StackExchange/dnscontrol/v3/commands.printOrRunCorrections(0xc000bc806a, 0x6, 0xc000bc8070, 0xa, 0xc000[22](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:22)0a00, 0x52, 0xa0, 0x1ae9a50, 0x[23](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:23)39060, 0x1, ...)
	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:[24](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:24)7 +0xd5
github.com/StackExchange/dnscontrol/v3/commands.run(0x7ffe9a0549f2, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:145 +0x567
github.com/StackExchange/dnscontrol/v3/commands.Push(...)
	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:92
github.com/StackExchange/dnscontrol/v3/commands.glob..func8.1(0xc000554000, 0xd, 0x10)
	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:63 +0xde
github.com/urfave/cli/v2.(*Command).Run(0xc000[27](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:27)3440, 0xc0004c92c0, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0004aa340, 0x1ad9e80, 0xc000040090, 0xc00003c1e0, 0x6, 0x6, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:[31](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:31)3 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/StackExchange/dnscontrol/v3/commands.Run(0xc000045200, 0x60, 0xb)
	/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:65 +0x2a7
main.main()
	/go/src/github.com/StackExchange/dnscontrol/main.go:[35](https://github.com/itwzhp/infrastruktura/runs/5422959457?check_suite_focus=true#step:4:35) +0x11d
```

**Comment by karol-gro** [comment]
As a note: we use version 3.14.0

**Comment by tlimoncelli** [comment]
Hi there!

I'm sorry to say that this is a real bug.  I can reproduce it by running the "pager1201" integration test.  This test is disabled for CLOUDFLAREAPI by mistake.

The problem is that the Cloudflare API only accepts 1000 changes per call.  To fix this, DNSControl needs to split up the requests into smaller groups.  It does not do that today.


Workaround: Push 900 changes at a time. 
1. Comment out all but 900 records.
2. Run: `dnscontrol push --domains zhp.pl --providers cloudflare`
3. Uncomment 900 records.
3. repeat.
4. After all records are pushed, normal `dnscontrol push` will be sufficient. Typical changes are smaller than 1000 changes.

If you are interested in fixing this, I would welcome a PR.

I can reproduce the bug with https://github.com/StackExchange/dnscontrol/pull/1442.  In that PR I enable the "pager1201" test and you can see the failure happening [when CircleCI runs](https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/492/workflows/630bc7f5-3d31-492d-a5c5-500785dccd8d/jobs/2865).

You can reproduce the test with this command:

```
export CLOUDFLAREAPI_DOMAIN='INSERT_DOMAIN'
export CLOUDFLAREAPI_TOKEN='INSERT_TOKEN'
go test -v -verbose -provider CLOUDFLAREAPI -cfworkers=false  -start 20 -end 22
```

Tom

P.S.  I am impressed by https://github.com/itwzhp/infrastruktura!  It is exactly how I hoped people would use this software!

**Comment by tlimoncelli** [comment]
@karol-gro That's ok.

This is improved by https://github.com/StackExchange/dnscontrol/pull/1531 (it no longer causes a crash).  Hopefully we can fix it 100% in the future.
