### ISSUE TITLE
Preview failing with interface {} is nil, not float64

### ISSUE THREAD

**Issue by chrisbrownie** [StackExchange/dnscontrol#1451]
I've had DNSControl working well for some time, and recently it's begun failing with the error below:

```panic: interface conversion: interface {} is nil, not float64```

This occurs when running `dnscontrol preview` via either my normal GitHub Actions method, or when running dnscontrol (`dnscontrol v3.15.0 ("eb81a7f4e54e4d48b421d6003eae151480b2fea9") built 08 Mar 22 05:52 AEDT)`) locally.

I've tried emptying the config file for this specific zone and it still fails, so to the best of my knowledge this failure occurs when dnscontrol is trying to retrieve the current zone file from the provider, rather than anything local.

I saw #1436 but my go-fu is not strong enough to discern whether this is the same problem or not. Full error below.

```
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).nativeToRecord(0x11, {0xc000a56610, 0x10}, {{0xeedd6a0, 0xed5af0bdb, 0x0}, {0xeedd6a0, 0xed5af0bdb, 0x0}, {0xc000312ad7, ...}, ...})
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/cloudflareProvider.go:641 +0x5b4
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).getRecordsForDomain(0xc0000d4050, {0xc0000390c0, 0x10}, {0xc000a56610, 0x10})
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/rest.go:38 +0x1d3
github.com/StackExchange/dnscontrol/v3/providers/cloudflare.(*cloudflareProvider).GetDomainCorrections(0xc0000d4050, 0xc00021ea50)
        /home/runner/work/dnscontrol/dnscontrol/providers/cloudflare/cloudflareProvider.go:161 +0xa5
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x19ad5a3, 0xc}, {0x0, 0x0}, 0x0, {{...}, 0x0}}, {0x0, 0x0}}, {{0x19aa095, ...}}, ...}, ...)
        /home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:138 +0x8d8
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
        /home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:87
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0xc0000c4400)
        /home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:25 +0x8b
github.com/urfave/cli/v2.(*Command).Run(0xc0002c0a20, 0xc000502280)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc00026a000, {0x1bd75a0, 0xc0000aa078}, {0xc0000a43a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc0000862a0, 0x19abbd4})
        /home/runner/work/dnscontrol/dnscontrol/commands/commands.go:65 +0x2a9
main.main()
        /home/runner/work/dnscontrol/dnscontrol/main.go:35 +0x134
```

**Comment by tlimoncelli** [comment]
Hi there!  Thanks for reporting this!

The stack trace points to a bunch of code that is pretty brittle.

I'm going to guess that there's a SRV record with a missing priority, weight, or port.  As a work-around, try fixing that SRV record or deleting it.  I'll look into fixing the code.

**Comment by tlimoncelli** [comment]
I think the code at https://github.com/StackExchange/dnscontrol/pull/1452 will fix this problem.  Could you compile it and give it a try?

**Comment by chrisbrownie** [comment]
That did it, Tom. Thank you!

**Comment by tlimoncelli** [comment]
Glad to help!
