### ISSUE TITLE
Compatibility issues with Go 1.19 (invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by WhoAmI0501** [StackExchange/dnscontrol#1695]
I am experiencing some issues, if I compile dnscontrol with Go 1.19 (to be detailed: golang:alpine and golang:bullseye).

The README states, that dnscontrol is compatible with all Go versions above 1.16, but if I compile it with Go 1.19, I only see the following errors:
```
### golang:alpine ###
/tmp/dnscontrol # ./dnscontrol
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8bd506]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000292000?, {0xc000240240?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x19fe200, 0xc0000cb100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0001e53b0, {0x19fe200?, 0xc0000cb100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x19fe200, 0xc0000cb100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x1a027e0?, 0xc0000145a0}, 0x2bd8c27)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x1a027e0, 0xc0000145a0}, 0x0?)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc0000c4da0?, 0xc0000f1980?})
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
/tmp/dnscontrol # 
```
```
### golang:bullseye ###
root@b995d368fa38:/tmp/dnscontrol# ./dnscontrol 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8bd426]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000280000?, {0xc000292000?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x19fe200, 0xc0000c9100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0001e33b0, {0x19fe200?, 0xc0000c9100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x19fe200, 0xc0000c9100}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x1a027e0?, 0xc0000145a8}, 0x2bd9618)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x1a027e0, 0xc0000145a8}, 0x0?)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc0000c2da0?, 0xc0000ef980?})
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
root@b995d368fa38:/tmp/dnscontrol# 
```

If I compile dnscontrol with Go 1.18, everything is fine.

**Comment by WhoAmI0501** [comment]
It seems like this was caused by my misconfigured build environment. From the point where i adapted my Dockerfile to the one of this project, my build pipeline produced a running executable and everything was fine.

**Comment by dan-r95** [comment]
Can you elaborate on what you configured wrong in your build env?

**Comment by tlimoncelli** [comment]
I'm curious about how this happens too.  I stumbled upon this problem but I didn't keep good notes.

**Comment by WhoAmI0501** [comment]
Before (didnt worked):
```Dockerfile
FROM golang:1.19-alpine AS go-builder

WORKDIR /tmp

RUN set -ex && \
    apk upgrade --no-cache && \
    apk add --no-cache jq && \
    RELEASE=$(wget -O- https://api.github.com/repos/StackExchange/dnscontrol/releases/latest 2>/dev/null| jq -r '.tag_name') && \
    wget https://github.com/StackExchange/dnscontrol/archive/refs/tags/${RELEASE}.tar.gz && \
    tar xf ${RELEASE}.tar.gz && \
    mv dnscontrol-* dnscontrol

WORKDIR /tmp/dnscontrol

RUN go build -o dnscontrol && \
    ./dnscontrol


FROM alpine:latest

ENV TZ=Europe/Berlin

COPY --from=go-builder /tmp/dnscontrol/dnscontrol /usr/local/bin/dnscontrol
```

After (worked):
```Dockerfile
FROM golang:1.19-alpine AS dnscontrol-builder

# prepare build environment
WORKDIR /go/src/github.com/StackExchange/
ENV GO111MODULE on
RUN set -ex && \
    apk upgrade --no-cache && \
    apk add --no-cache jq ca-certificates build-base && \
    update-ca-certificates && \
    RELEASE=$(wget -O- https://api.github.com/repos/StackExchange/dnscontrol/releases/latest 2>/dev/null| jq -r '.tag_name') && \
    wget https://github.com/StackExchange/dnscontrol/archive/refs/tags/${RELEASE}.tar.gz -O- | tar xzf - && \
    mv dnscontrol-* dnscontrol

# compile and test
WORKDIR /go/src/github.com/StackExchange/dnscontrol/
RUN go build -v -trimpath -buildmode=pie -ldflags="-s -w" && \
    cp dnscontrol /go/bin/dnscontrol && \
    dnscontrol version


FROM alpine:latest

ENV TZ=Europe/Berlin

COPY --from=dnscontrol-builder /etc/ssl/certs /etc/ssl/certs
COPY --from=dnscontrol-builder /go/src/github.com/StackExchange/dnscontrol/dnscontrol /usr/local/bin/dnscontrol
```

**Comment by bits01** [comment]
@tlimoncelli This is still a problem on Ubuntu 20.04 with go version go1.19.3 linux/amd64

**Comment by tlimoncelli** [comment]
Re-opening this ticket. I thought this was Debian-specific.  It turns out to be a problem on all Linux systems and FreeBSD as well.
