### ISSUE TITLE
Azure CI/CD pipeline temporarily disabled

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1868]
github actions secret `AZURE_DNS_DOMAIN` has been removed to disable testing that provider.
To re-enable it, add a github action secret `AZURE_DNS_DOMAIN` with value `dnscontrol-azure.com` or whatever DNS domain is to be used in the future.

Also: The same variable must be added back in CCI: [link](https://app.circleci.com/settings/project/github/StackExchange/dnscontrol/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2FStackExchange%2Fdnscontrol)

Why?

For some reason this zone is getting the folllowing error:

```
tlimworkm1:~/git/dnscontrol/integrationTest$ dnscontrol preview
******************** Domain: dnscontrol-azure.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102e0bce4]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/azuredns.nativeToRecords(0x140000aa3c0, {0x140000488b8, 0x14})
	/Users/tlimoncelli/git/dnscontrol/providers/azuredns/azureDnsProvider.go:421 +0x6a4
github.com/StackExchange/dnscontrol/v3/providers/azuredns.(*azurednsProvider).getExistingRecords(0x14000966030, {0x1400070d128, 0x14})
	/Users/tlimoncelli/git/dnscontrol/providers/azuredns/azureDnsProvider.go:174 +0x19c
github.com/StackExchange/dnscontrol/v3/providers/azuredns.(*azurednsProvider).GetDomainCorrections(0x14000966030, 0x1400041e0f0)
	/Users/tlimoncelli/git/dnscontrol/providers/azuredns/azureDnsProvider.go:193 +0x48
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x1034509bb, 0xc}, {0x0, 0x0}, 0x0, {{...}, 0x0}}, {0x0, 0x0}}, {{0x10344d44f, ...}}, ...}, ...)
	/Users/tlimoncelli/git/dnscontrol/commands/previewPush.go:185 +0xa88
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
	/Users/tlimoncelli/git/dnscontrol/commands/previewPush.go:100
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0x14000407400?)
	/Users/tlimoncelli/git/dnscontrol/commands/previewPush.go:26 +0x78
github.com/urfave/cli/v2.(*Command).Run(0x14000407400, 0x140002bee80, {0x140006a19d0, 0x1, 0x1})
	/Users/tlimoncelli/go/pkg/mod/github.com/urfave/cli/v2@v2.23.5/command.go:271 +0x804
github.com/urfave/cli/v2.(*Command).Run(0x140000cb400, 0x140002bed40, {0x140001ae000, 0x2, 0x2})
	/Users/tlimoncelli/go/pkg/mod/github.com/urfave/cli/v2@v2.23.5/command.go:264 +0xa24
github.com/urfave/cli/v2.(*App).RunContext(0x14000546000, {0x103babba0?, 0x140001a6008}, {0x140001ae000, 0x2, 0x2})
	/Users/tlimoncelli/go/pkg/mod/github.com/urfave/cli/v2@v2.23.5/app.go:329 +0x5dc
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/tlimoncelli/go/pkg/mod/github.com/urfave/cli/v2@v2.23.5/app.go:306
github.com/StackExchange/dnscontrol/v3/commands.Run({0x14000118e50?, 0x10344ef6d?})
	/Users/tlimoncelli/git/dnscontrol/commands/commands.go:64 +0x330
main.main()
	/Users/tlimoncelli/git/dnscontrol/main.go:34 +0x180
```

**Comment by vatsalyagoel** [comment]
@tlimoncelli are they any dangling records in the dnscontrol-azure.com zone in Azure? Looks like a null pointer dereference. 

Based on my understanding, it could be happening because the record may have a null or whitespace entry.

**Comment by tlimoncelli** [comment]
It has been re-enabled.

The problem was a record with a null target.  I deleted it from the portal. I don't know how such a thing got created, but I don't think it is likely to happen again.
