### ISSUE TITLE
MSDNS: User+Pass authentication not working

### ISSUE THREAD

**Issue by shodges-vermeer** [StackExchange/dnscontrol#2278]
Despite what I said in #2273 , I don't believe user+pass authentication is working.

I'm getting the following error...
`INFO: PowerShell commands will run on "windowshost"
panic: Could not setup credentials: Could not convert password to secure string: ConvertTo-SecureString : The 'ConvertTo-SecureString' command was found in the module 'Microsoft.PowerShell.Security', 
but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'.
At line:1 char:27
+ $goPass95f064b411899ca1 = ConvertTo-SecureString -String '***' ...
+                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertTo-SecureString:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
: $goPass95f064b411899ca1 = ConvertTo-SecureString -String '***' -AsPlainText -Force

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/providers/msdns.newPowerShell(0x224a360?)
	/home/runner/work/dnscontrol/dnscontrol/providers/msdns/powershell.go:55 +0x2ba
github.com/StackExchange/dnscontrol/v3/providers/msdns.newDNS(0x2245e60?, {0xc0001e61b0?, 0xc00047a578?, 0x5?})
	/home/runner/work/dnscontrol/dnscontrol/providers/msdns/msdnsProvider.go:63 +0x150
github.com/StackExchange/dnscontrol/v3/providers.CreateDNSProvider({0xc00047a578?, 0xc000668f60?}, 0xc000268230?, {0x0, 0x0, 0x0})
	/home/runner/work/dnscontrol/dnscontrol/providers/providers.go:102 +0x95
github.com/StackExchange/dnscontrol/v3/commands.InitializeProviders(0xc000670420, 0xa?, 0x0?)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:297 +0x8ba
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x2549efa, 0xc}, {0x0, 0x0}, 0x0, {{...}, {...}, 0x0, 0x0}}, {0x0, ...}}, ...}, ...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:126 +0xc7
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:103
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0xc000190dc0?)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:29 +0xa6
github.com/urfave/cli/v2.(*Command).Run(0xc000190dc0, 0xc000464680, {0xc000267a60, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc000288580, 0xc000464500, {0xc00007c040, 0x3, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0002063c0, {0x27b0c30?, 0xc00003e0a8}, {0xc00007c040, 0x3, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc00003d450?, 0x2548272?})
	/home/runner/work/dnscontrol/dnscontrol/commands/commands.go:70 +0x325
main.main()
	/home/runner/work/dnscontrol/dnscontrol/main.go:37 +0x15b`

cred.json is (roughly) as follows...
{
    "msdns_": {
        "TYPE": "MSDNS",
        "pssession": "windowshost",
        "psusername": "$MSDNS_USERNAME",
        "pspassword": "$MSDNS_PASSWORD"
    },
    "notifications": {
        "teams_url": "$TEAMS_NOFIY_URL"
    }
}

**Comment by shodges-vermeer** [comment]
In the same GitHub workflow, I've successfully ran the command that's failing.

```powershell
ConvertTo-SecureString -String 'asdf' -AsPlainText -Force
```

**Comment by tlimoncelli** [comment]
`ConvertTo-SecureString` doesn't appear in the code.Hmm...

I admit that I'm not a powershell expert.  I kind of guessed my way through the MSDNS provider.  In hindsight, the code isn't very testable.  It would be better if we had an external tool (written is PowerShell) that we called.  (would love to collaborate if interested)

**Comment by shodges-vermeer** [comment]
`ConvertTo-SecureString` is in the [core provider repository](https://github.com/bhendo/go-powershell/blob/master/middleware/session_config.go). Essentially PowerShell won't allow you to authenticate with a plaintext string, so you have to convert it to a securestring object first.

I'm good with PowerShell, but have no experience with Go. What're you thinking in regards to an external PS tool?

**Comment by tlimoncelli** [comment]
[shodges-vermeer](https://github.com/shodges-vermeer)
> I'm good with PowerShell, but have no experience with Go. What're you thinking in regards to an external PS tool?

Right now Dnscontrol generates the powershell command on demand then executes it.  The generated command is slightly different if you are deleting an MX record, an A record, etc.

Because we're generating a command line, we don't do much error checking.

I think it would be better if DNSControl always called the same powershell script, and the powershell script did the right thing based on the record type (A, MX, etc).   We could test the script independently.  The script itself could be more sophisticated. It could do better error checking, take special care of special cases such as NAPTR records, etc.

I imagine it would be called like:

name_of_script add A zonename.com host123 1.2.3.4
name_of_script remove A zonename.com host123 1.2.3.4

I'm not entirely sure what the syntax should be.  Maybe it should be separate scripts for add, modify, modify, delete.  Modify and delete need to search for an existing record and then operate on it... Maybe there's a better way to specify how to search for a record that we know exists (does `Get-DnsServerResourceRecord` include a GUID or other unique identifier we can refer to?)

Anyway... the benefit of doing it this way is that it would be a separate PowerShell scripts that can be independently tested. I know PS has a lot of good testing tools that would help prevent regressions.  Heck, maybe people will use the tool on its own if the syntax is cleaner.

**Comment by tlimoncelli** [comment]
About the user+pass authentication not working: I don't have the ability to test this. I could use a volunteer to debug this one!

**Comment by shodges-vermeer** [comment]
Hey, I apologize for such a delay on this. Another project took most of my time.

As for the PS script - I don't think that I'm going to be able to help with that. It's more complicated than what I can do. I'm sorry about that.

User+Pass authentication - I can absolutely help with this, we have MSDNS setup for a few of our domains. How can I help?

**Comment by tlimoncelli** [comment]
No worries. Glad you're back :) 

PS script: Understood!

User+Pass authentication: Help figure out why it fails and propose a fix.  All the powershell gets generated in `providers/msdns/powershell.go`.  Maybe we're just not using github.com/bhendo/go-powershell correctly?

**Comment by shodges-vermeer** [comment]
It doesn't look like go-powershell is being maintained, and was only setup as a copy for bhendo (https://github.com/bhendo/go-powershell/issues/7)

I can dig into it and see why it's not working, but wasn't sure if you wanted to keep using this plugin given the above. I don't have any go experience, but if you know of a different one I can try and help rewrite portions to work with a new plugin.

**Comment by tlimoncelli** [comment]
Wow  I forgot that module wasn't maintained. I've opened https://github.com/StackExchange/dnscontrol/issues/2337 as a reminder. If we need to make changes to it, I'd be glad to fork it.

I'm going to guess that the feature to run in a PSSession wasn't tested very well... or we aren't using it correctly.  I could really use your help narrowing down the problem.  The PSSession stuff is all in go-powershell/middleware/session_config.go.  Maybe add some debug statements to see what command is being executed?

**Comment by tlimoncelli** [comment]
https://github.com/StackExchange/dnscontrol/issues/2337 replaces this.  Closing this.
