### ISSUE TITLE
BUG: ROUTE53: diff2 crashes when trying to IGNORE_NAME/IGNORE_TARGET with R53_ALIAS

### ISSUE THREAD

**Issue by JBOClara** [StackExchange/dnscontrol#2285]
Error with the new diff2 production test

```
./.tools/dnscontrol version
dnscontrol  (bcf590f649ac94b03ea994ff9b5d76cc921c7f89) built 16 Apr 23 21:19 CEST
```

```
./.tools/dnscontrol preview --diff2=true
[INFO: Diff2 algorithm in use.]
******************** Domain: customer.com
2023/04/17 16:04:34 record.go:366: No such DNS type as ("R53_ALIAS")
make: *** [preview] Error 1
```

**Comment by JBOClara** [comment]
The bug doesn't appear without "--diff2=true"

I've a pending diff like which are visible with diff2=false:

```
#1:
- DELETE TXT _ed.domain.co.uk "heritage=external-dns,external-dns/owner=eks-customer-prod-cluster,external-dns/resource=ingress/default/ingress" ttl=300
- DELETE R53_ALIAS domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=ROUTE53_ZONE_ID ttl=300 type=A zone_id=ROUTE53_ZONE_ID
- DELETE R53_ALIAS www.domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=ROUTE53_ZONE_ID ttl=300 type=A zone_id=ROUTE53_ZONE_ID
```

dnsconfig.js:

```javascript
// Dns Definition for customer-Digital/Days Of Wonder

var DNS = NewDnsProvider("r53")
var DNS_OVH = NewDnsProvider("ovh")
var REG_OVH = NewRegistrar("ovh")
var REG_NONE = NewRegistrar("none")


D("domain.co.uk", REG_NONE,
    DnsProvider(DNS),
    DefaultTTL(3600),
    IGNORE_NAME('account'),
    IGNORE_NAME('gift'),
    IGNORE_NAME('rules'),
    IGNORE_NAME('_000000009999999999'),
    IGNORE_NAME('account-staging'),
    IGNORE_NAME('gift-staging'),
    IGNORE_NAME('rule'),
    IGNORE_NAME('account-restyle'),
    IGNORE_NAME('gift-restyle'),
    IGNORE_TARGET('**.acm-validations.aws.', 'CNAME'),
    IGNORE_NAME('_ed.**', 'TXT'),
    MX('@', 0, 'mxa-00000000.gslb.pphosted.com.'),
    MX('www', 0, 'mxb-00000000.gslb.pphosted.com.'),
    A('@', '85.200.140.216', TTL("300")),
    A('www', '85.200.140.216', TTL("300")),
    A('api', '85.200.140.212'),
    TXT('@', 'google-site-verification=REDACTED'),
    TXT('@', 'MS=REDACTED'),
    TXT('@', 'v=spf1 include:spf.protection.outlook.com include:spf-REDACTED.pphosted.com include:_spf.customer.net -all'),
    TXT('REDACTED._domainkey', 'v=DKIM1; t=s; p=REDACTED', AUTOSPLIT),
    CNAME('autodiscover', 'autodiscover.outlook.com.'),
    TXT('_dmarc', 'v=DMARC1; p=reject; fo=1'),
    CNAME('email', 'u400000.wl000.sendgrid.net.'),
    CNAME('s1._domainkey', 's1.domainkey.u400000.wl000.sendgrid.net.'),
    CNAME('s2._domainkey', 's2.domainkey.u400000.wl000.sendgrid.net.')
)
```


With --full 

```
/.tools/dnscontrol preview --domains "domain.co.uk" --full --diff2
[INFO: Diff2 algorithm in use.]
******************** Domain: domain.co.uk
----- Getting nameservers from: r53
----- DNS Provider: r53...
2023/04/17 16:52:19 record.go:366: No such DNS type as ("R53_ALIAS")
````

**Comment by tlimoncelli** [comment]
Oh that's interesting!  If I read this right, there is no R53_ALIAS in the dnsconfig.js file. Instead, you want to *ignore* an R53_ALIAS that is injected elsewhere.  The problem is that IGNORE_NAME or IGNORE_TARGET commands aren't working the same way as without `--diff2`.

Does the problem go away if you change:

```
    IGNORE_TARGET('**.acm-validations.aws.', 'CNAME'),
```

to

```
    IGNORE_TARGET('**.acm-validations.aws.', '*'),
```

Or maybe:

```
    IGNORE_TARGET('**.acm-validations.aws.', 'CNAME,R53_ALIAS'),
```

**Comment by JBOClara** [comment]
## For `IGNORE_TARGET('**.acm-validations.aws.', 'CNAME,R53_ALIAS'),`

Without diff2
```
dnscontrol preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
panic: Invalid rType for IGNORE_TARGET CNAME,R53_ALIAS


goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/pkg/diff.compileIgnoredTargets({0xc0006524c0, 0x1, 0xc000652508?})
	/home/runner/work/dnscontrol/dnscontrol/pkg/diff/diff.go:384 +0x27e
github.com/StackExchange/dnscontrol/v3/pkg/diff.New(0xc0009cf7a0, {0xc000652508, 0x1, 0x1})
	/home/runner/work/dnscontrol/dnscontrol/pkg/diff/diff.go:43 +0x86
github.com/StackExchange/dnscontrol/v3/providers/route53.(*route53Provider).GetZoneRecordsCorrections(0xc000001480, 0xc0009cf7a0, {0xc0000a2000, 0x2c, 0x40})
	/home/runner/work/dnscontrol/dnscontrol/providers/route53/route53Provider.go:292 +0x4b7
github.com/StackExchange/dnscontrol/v3/pkg/zonerecs.CorrectZoneRecords({0x2cddd110, 0xc000001480}, 0xc0009ce900)
	/home/runner/work/dnscontrol/dnscontrol/pkg/zonerecs/zonerecords.go:33 +0xd3
github.com/StackExchange/dnscontrol/v3/commands.run.func1(0x0?, 0xc00059d7a8, 0xc00059d778, {0x27333b0, 0x30fea20}, 0x0, 0xc000131725, 0xc000131728, 0x0?, {0x27255f0, ...}, ...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:223 +0x751
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x24ca013, 0xc}, {0x0, 0x0}, 0x0, {{...}, {...}, 0x0, 0x0}}, {0x0, ...}}, ...}, ...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:252 +0x39c
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:109
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0xc00020edc0?)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:30 +0xa6
github.com/urfave/cli/v2.(*Command).Run(0xc00020edc0, 0xc0001a1c40, {0xc0000f5ec0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc0004289a0, 0xc0001a1ac0, {0xc0001a0040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0000fc000, {0x272a350?, 0xc0001a2008}, {0xc0001a0040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc0001807e0?, 0x24c84b4?})
	/home/runner/work/dnscontrol/dnscontrol/commands/commands.go:70 +0x325
main.main()
	/home/runner/work/dnscontrol/dnscontrol/main.go:37 +0x15b
```

Same test with diff2 output:

```
dnscontrol preview --domains "domain.co.uk" --diff2
[INFO: Diff2 algorithm in use.]
******************** Domain: domain.co.uk
2023/04/17 18:33:28 record.go:366: No such DNS type as ("R53_ALIAS")
```

## for `IGNORE_TARGET('**.acm-validations.aws.', '*'),`

```
dnscontrol preview --domains "unboxnow.co.uk" --diff2
[INFO: Diff2 algorithm in use.]
******************** Domain: unboxnow.co.uk
2023/04/17 18:34:41 record.go:366: No such DNS type as ("R53_ALIAS")
```

Without diff2

```
dnscontrol preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
panic: Invalid rType for IGNORE_TARGET *

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/pkg/diff.compileIgnoredTargets({0xc000488428, 0x1, 0xc000488470?})
	/home/runner/work/dnscontrol/dnscontrol/pkg/diff/diff.go:384 +0x27e
github.com/StackExchange/dnscontrol/v3/pkg/diff.New(0xc000c14b40, {0xc000488470, 0x1, 0x1})
	/home/runner/work/dnscontrol/dnscontrol/pkg/diff/diff.go:43 +0x86
github.com/StackExchange/dnscontrol/v3/providers/route53.(*route53Provider).GetZoneRecordsCorrections(0xc000027300, 0xc000c14b40, {0xc0006cc000, 0x2c, 0x40})
	/home/runner/work/dnscontrol/dnscontrol/providers/route53/route53Provider.go:292 +0x4b7
github.com/StackExchange/dnscontrol/v3/pkg/zonerecs.CorrectZoneRecords({0x2da43bf8, 0xc000027300}, 0xc0000efb00)
	/home/runner/work/dnscontrol/dnscontrol/pkg/zonerecs/zonerecords.go:33 +0xd3
github.com/StackExchange/dnscontrol/v3/commands.run.func1(0x0?, 0xc0004837a8, 0xc000483778, {0x27333b0, 0x30fea20}, 0x0, 0xc0003d7725, 0xc0003d7728, 0x0?, {0x27255f0, ...}, ...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:223 +0x751
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x24ca013, 0xc}, {0x0, 0x0}, 0x0, {{...}, {...}, 0x0, 0x0}}, {0x0, ...}}, ...}, ...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:252 +0x39c
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:109
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0xc00020edc0?)
	/home/runner/work/dnscontrol/dnscontrol/commands/previewPush.go:30 +0xa6
github.com/urfave/cli/v2.(*Command).Run(0xc00020edc0, 0xc000003cc0, {0xc000001830, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc000428b00, 0xc000003b40, {0xc0001a0040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc00001a000, {0x272a350?, 0xc0001a2008}, {0xc0001a0040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc0001808a0?, 0x24c84b4?})
	/home/runner/work/dnscontrol/dnscontrol/commands/commands.go:70 +0x325
main.main()
	/home/runner/work/dnscontrol/dnscontrol/main.go:37 +0x15b
```

**Comment by tlimoncelli** [comment]
Thank you for running those tests.  Helps me narrow down the issue.

Question: Do you want to delete or ignore these records?

```
- DELETE R53_ALIAS domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=ROUTE53_ZONE_ID ttl=300 type=A zone_id=ROUTE53_ZONE_ID
- DELETE R53_ALIAS www.domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=ROUTE53_ZONE_ID ttl=300 type=A zone_id=ROUTE53_ZONE_ID
```

**Comment by tlimoncelli** [comment]
Brian: @tresni 
Any thoughts?

P.S. I'm more interested in debugging the diff2 case.

**Comment by JBOClara** [comment]
I don't want to delete these records.

This works with diff2=false
```
IGNORE_NAME('*', 'R53_ALIAS'),
```

Although it's not urgent for me right now, I wanted to provide feedback on the issue I experienced with `diff2`.

**Comment by tlimoncelli** [comment]
[JBOClara](https://github.com/JBOClara)

> Although it's not urgent for me right now, I wanted to provide feedback on the issue I experienced with `diff2`.

I appreciate you reporting this!  You've prevented hundreds of other people hitting this bug in production.

I'll work on this over the next few days.

**Comment by scruffydan** [comment]
Not sure if this is the same issue or not but when I run `dnscontrol --diff2 push` on a zone with the `NO_PURGE` option and one A record set by dnscontrol I get the following:

```
FAILURE! operation error Route 53: ChangeResourceRecordSets, 2 validation error(s) found.
- missing required field, ChangeResourceRecordSetsInput.ChangeBatch.Changes[0].Action.
- missing required field, ChangeResourceRecordSetsInput.ChangeBatch.Changes[0].ResourceRecordSet.
``` 

When I run `dnscontrol --diff2 preview ` I get no errors but  `Done. 1 corrections.`

when I don't use `diff2` both preview and push run without errors

**Comment by tlimoncelli** [comment]
@scruffydan Yes, that's probably the same  issue.

It turns out the integration tests for diff2 don't cover this situation.  I think I have a lot of work ahead of me.

**Comment by tlimoncelli** [comment]
I've updated the integration tests and fixed the bugs that I found. I haven't investigated the R53_ALIAS issue yet, but that's next.  I would appreciated it if you could try the `tlim_integrationdebug` branch (PR https://github.com/StackExchange/dnscontrol/pull/2292) and let me know if that changes/improves things for you.

**Comment by JBOClara** [comment]
I've no more diff in my environment but I already get an error:

```
~/.asdf/installs/golang/1.18/packages/bin/dnscontrol preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
Done. 0 corrections.


~.asdf/installs/golang/1.18/packages/bin/dnscontrol preview --domains "domain.co.uk" --diff2
Incorrect Usage: flag provided but not defined: -diff2

NAME:
   dnscontrol preview - read live configuration and identify changes to be made, without applying them

USAGE:
   dnscontrol preview command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --config value                                             File containing dns config in javascript DSL (default: "dnsconfig.js")
   --dev                                                      Use helpers.js from disk instead of embedded copy (default: false)
   --variable value, -v value [ --variable value, -v value ]  Add variable that is passed to JS
   --ir value                                                 Read IR (json) directly from this file. Do not process DSL at all
   --creds value                                              Provider credentials JSON file (or !program to execute program that outputs json) (default: "creds.json")
   --providers value                                          Providers to enable (comma separated list); default is all. Can exclude individual providers from default by adding '"_exclude_from_defaults": "true"' to the credentials file for a provider
   --domains value                                            Comma separated list of domain names to include
   --notify                                                   set to true to send notifications to configured destinations (default: false)
   --expect-no-changes                                        set to true for non-zero return code if there are changes (default: false)
   --no-populate                                              Use this flag to not auto-create non-existing zones at the provider (default: false)
   --full                                                     Add headings, providers names, notifications of no changes, etc (default: false)
   --help, -h                                                 show help
```

**Comment by tlimoncelli** [comment]
Try moving the `--diff2` to just after `dnscontrol`.

**Comment by JBOClara** [comment]
> Try moving the `--diff2` to just after `dnscontrol`.

```
dnscontrol --diff2 preview --domains "domain.co.uk"
[INFO: Diff2 algorithm in use.]
******************** Domain: domain.co.uk
2023/04/23 18:11:38 record.go:366: No such DNS type as ("R53_ALIAS")
```

**Comment by tlimoncelli** [comment]
The good news is that I have been able to repro the bug: See https://github.com/StackExchange/dnscontrol/pull/2294

To recap: (please confirm)

* This bug only appears in diff2 (i.e. The bug isn't seen in `--diff2=false`)
* The bug appears if you have an existing R53_ALIAS record.

**Comment by scruffydan** [comment]
I don't have an `R53_ALIAS` in my zone. Just `A`, `CNAME`, and `TXT` records. But I am using the `NO_PURGE `

**Comment by tlimoncelli** [comment]
@scruffydan thanks for the clarification!  I've updated the 2nd bullet to be "...which is being ignored by NO_PURGE". You do have an R53_ALIAS record in your zone (on the server), just not in your dnsconfig.js.

Well, the good news is that I believe the commit I just made to https://github.com/StackExchange/dnscontrol/pull/2294 fixes the problem.

The problem was the formatting code for the new informational message about which records are being ignored.  It was using a function call that doesn't know about R53_ALIAS.  Thank heavens it was just a buggy formatting statement; not some fundamental issue with the new diff2 algorithm. 😌 

diff2 unifies the processing of NO_PURGE, IGNORE_NAME and IGNORE_TARGET.  Previously NO_PURGE was a bit of a hack.  Now it all is done in one unified module that handles anything that dnscontrol shouldn't touch... appropriately called `handsoff.go`

Take a look at https://github.com/StackExchange/dnscontrol/pull/2294 (the `tlim_r53alias_try1` branch) and tell me if that solves the problem for you.

**Comment by JBOClara** [comment]
> The good news is that I have been able to repro the bug: See #2294
> 
> To recap: (please confirm)
> 
> * This bug only appears in diff2 (i.e. The bug isn't seen in `--diff2=false`)
> * The bug appears if you have an existing R53_ALIAS record which is being ignored by NO_PURGE

And I've the exact opposite of @scruffydan, in my zone 

- R53_ALIAS 
- no NO_PURGE

**Comment by scruffydan** [comment]
@tlimoncelli can you link instruction to build your test branch that solves the issue? or send me a precompiled binary for Macos13 on M1

**Comment by tlimoncelli** [comment]
@scruffydan Gladly!

Clone the repo:

```
git clone https://github.com/StackExchange/dnscontrol.git
```
(or use whatever method you like from https://github.com/StackExchange/dnscontrol  ... click on the green "code" button for options)

Switch to the branch and compile it.  You'll need Go installed: https://go.dev/

```
cd dnscontrol
git checkout tlim_r53alias_try1
go install
```

**Comment by scruffydan** [comment]
Thanks for the instructions. I was able to test this and while I no longer the error however no changes are applied to the A record I am testing when using `diff2` 

Without `diff2` the A record is updated correctly

**Comment by tlimoncelli** [comment]
@scruffydan Please start a new issue for your bug related to `A` records.  (Sorry, I should have asked you to do that earlier)

**Comment by tlimoncelli** [comment]
@JBOClara:


Here's my theory: The old code stores R53_ALIAS records as a CNAME or A record with a flag that means "well, it's not really a CNAME... its an Amazon alias for a CNAME" (or A record).   The new code stores R53_ALIAS records as an R53_ALIAS with a flag that indicates if this aliasing a CNAME or an A record.  The IGNORE code is a bit confused.

We can test this by adding this code to your `D()`:

```
    IGNORE_TARGET('**.acm-validations.aws.', 'R53_ALIAS'),
```

If that works for both with and without diff2, then we know that's the problem.

**Comment by JBOClara** [comment]
Same error:
```
 /tmp/dnscontrol/dnscontrol -v --diff2 preview --domains "domain.co.uk"
[INFO: Diff2 algorithm in use.]
******************** Domain: unboxnow.co.uk
2023/04/25 18:28:39 record.go:366: No such DNS type as ("R53_ALIAS")
```

But with your suggestion and without diff2:

```
/tmp/dnscontrol/dnscontrol -v preview --domains "unboxnow.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
panic: Invalid rType for IGNORE_TARGET R53_ALIAS

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/pkg/diff.compileIgnoredTargets({0x1400026c478, 0x1, 0x0?})
	/tmp/dnscontrol/pkg/diff/diff.go:384 +0x248
github.com/StackExchange/dnscontrol/v3/pkg/diff.New(0x14000a12a20, {0x1400026c4c0, 0x1, 0x1})
	/tmp/dnscontrol/pkg/diff/diff.go:43 +0x74
github.com/StackExchange/dnscontrol/v3/providers/route53.(*route53Provider).GetZoneRecordsCorrections(0x14000113280, 0x14000a12a20, {0x140002aa000, 0x2c, 0x40})
	/tmp/dnscontrol/providers/route53/route53Provider.go:292 +0x3c8
github.com/StackExchange/dnscontrol/v3/pkg/zonerecs.CorrectZoneRecords({0x12dc5f900, 0x14000113280}, 0x14000826a20)
	/tmp/dnscontrol/pkg/zonerecs/zonerecords.go:33 +0xd4
github.com/StackExchange/dnscontrol/v3/commands.run.func1(0x0?, 0x14000ed37d8, 0x14000ed37a8, {0x105d8d4e8, 0x106702740}, 0x0, 0x14000ed3755, 0x14000ed3758, 0x0?, {0x105d81d98, ...}, ...)
	/tmp/dnscontrol/commands/previewPush.go:218 +0x5f0
github.com/StackExchange/dnscontrol/v3/commands.run({{{{0x1055d65da, 0xc}, {0x0, 0x0}, 0x0, {{...}, {...}, 0x0, 0x0}}, {0x0, ...}}, ...}, ...)
	/tmp/dnscontrol/commands/previewPush.go:247 +0x2d4
github.com/StackExchange/dnscontrol/v3/commands.Preview(...)
	/tmp/dnscontrol/commands/previewPush.go:104
github.com/StackExchange/dnscontrol/v3/commands.glob..func7.1(0x1400022b340?)
	/tmp/dnscontrol/commands/previewPush.go:30 +0x7c
github.com/urfave/cli/v2.(*Command).Run(0x1400022b340, 0x14000270900, {0x14000031350, 0x3, 0x3})
	/Users/jboulanger/.asdf/installs/golang/1.18/packages/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x7b0
github.com/urfave/cli/v2.(*Command).Run(0x1400043af20, 0x14000270740, {0x1400018e050, 0x5, 0x5})
	/Users/jboulanger/.asdf/installs/golang/1.18/packages/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 +0x9d4
github.com/urfave/cli/v2.(*App).RunContext(0x140000a0000, {0x105d86520?, 0x140001b2008}, {0x1400018e050, 0x5, 0x5})
	/Users/jboulanger/.asdf/installs/golang/1.18/packages/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x604
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/jboulanger/.asdf/installs/golang/1.18/packages/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
github.com/StackExchange/dnscontrol/v3/commands.Run({0x14000048b90?, 0x1055d4ad7?})
	/tmp/dnscontrol/commands/commands.go:70 +0x3a8
main.main()
	/tmp/dnscontrol/main.go:37 +0x1bc
```

**Comment by tlimoncelli** [comment]
@JBOClara Could you make sure you're running the right binary?  I would expect some difference.

**Comment by JBOClara** [comment]
You have merged on master https://github.com/StackExchange/dnscontrol/pull/2292 

And I've complied from master:
```
/tmp/dnscontrol/dnscontrol --help
NAME:
   dnscontrol - dnscontrol is a compiler and DSL for managing dns zones

USAGE:
   dnscontrol [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command
   main:
     preview  read live configuration and identify changes to be made, without applying them
     push     identify changes to be made, and perform them
   debug:
     check     Check and validate dnsconfig.js. Output to stdout.  Do not access providers.
     print-ir  Output intermediate representation (IR) after running validation and normalization logic.
     version   Print version information
   utility:
     check-creds          Do a small operation to verify credentials (stand-alone)
     create-domains       DEPRECATED: Ensures that all domains in your configuration are activated at their Domain Service Provider (This does not purchase the domain or otherwise interact with Registrars.)
     fmt                  [BETA] Format and prettify a given file
     get-certs            Issue certificates via Let's Encrypt
     get-zones, get-zone  gets a zone from a provider (stand-alone)
     write-types          [BETA] Write a TypeScript declaration file in the current directory

GLOBAL OPTIONS:
   -v             Enable detailed logging (default: false)
   --allow-fetch  Enable JS fetch(), dangerous on untrusted code! (default: false)
   --diff2        Enable replacement diff algorithm (default: false)
   --help, -h     show help


 /tmp/dnscontrol/dnscontrol version
dnscontrol -dev
```

**Comment by JBOClara** [comment]
But here an an interesting point:

```
/tmp/dnscontrol/dnscontrol -v preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
Ignoring record _REDACTED CNAME due to IGNORE_NAME
Ignoring record _REDACTED CNAME due to IGNORE_TARGET
Ignoring record _ed TXT due to IGNORE_NAME
Ignoring record _REDACTED CNAME due to IGNORE_TARGET
Ignoring record account R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.account TXT due to IGNORE_NAME
Ignoring record gift R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.gift TXT due to IGNORE_NAME
Ignoring record rules R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.rules TXT due to IGNORE_NAME
Ignoring record _ed.www TXT due to IGNORE_NAME
1 correction (r53)
#1:
- DELETE R53_ALIAS domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED ttl=300 type=A zone_id=REDACTED
- DELETE R53_ALIAS www.domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED ttl=300 type=A zone_id=REDACTED

Done. 1 corrections.
```

the R53_ALIAS are not CNAME `acm-validations.aws`

They are :
```
- DELETE R53_ALIAS domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED ttl=300 type=A zone_id=REDACTED
- DELETE R53_ALIAS www.domain.co.uk REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED ttl=300 type=A zone_id=REDACTED
```

**Comment by tlimoncelli** [comment]
@JBOClara: I'm kind of stumped. I don't normally do this  but would you have time to do a screen share and debug this in real time?  I'm available Sunday [14:00](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=4&day=30&hour=14&min=0&sec=0&p1=224&p2=75&p3=24&p4=179&p5=136&p6=240) to [20:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=4&day=30&hour=20&min=0&sec=0&p1=224&p2=75&p3=24&p4=179&p5=136&p6=240).

**Comment by tlimoncelli** [comment]
I have a hunch that https://github.com/StackExchange/dnscontrol/pull/2294 (which has been merged) and PR https://github.com/StackExchange/dnscontrol/pull/2306 (which fixes https://github.com/StackExchange/dnscontrol/issues/2296) will fix the bug you reported.

Could you try `tlim_b2296_r53zoneid` and report back your results?

```
git clone https://github.com/StackExchange/dnscontrol.git
cd dnscontrol
git checkout tlim_b2296_r53zoneid
go install
```

**Comment by JBOClara** [comment]
The output with the master branch since you merge `tlim_b2296_r53zoneid`.

```
./dnscontrol -v --diff2 preview --domains "domain.co.uk"
[INFO: Diff2 algorithm in use.]
******************** Domain: domain.co.uk
1 correction (r53)
#1: INFO: 18 records not being deleted because of IGNORE*():
    domain.co.uk. R53_ALIAS k8s-REDACTED--REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED
    _9a70d167c39d4a8f33105abddbb87958.domain.co.uk. CNAME _a8b6e6981522dcf2f11701006c45a3c1.bbfvkzsszw.acm-validations.aws.
    _ed.domain.co.uk. TXT "heritage=external-dns,external-dns/owner=eks-CUSTOMER-prod-cluster,external-dns/resource=ingress/default/ingress"
    _ed.account-cl.domain.co.uk. TXT "heritage=external-dns,external-dns/owner=eks-CUSTOMER-prod-cluster,external-dns/resource=ingress/is/is"
    account.domain.co.uk. R53_ALIAS k8s-REDACTED--REDACTED.us-east-1.elb.amazonaws.com. atype=A zone_id=REDACTED
    ...and 13 more... (use --full to show all)
- DELETE _REDACTED.domain.co.uk CNAME _REDACTED.REDACTED.acm-validations.aws. ttl=60
- DELETE _REDACTED.domain.co.uk CNAME _REDACTED.REDACTED.acm-validations.aws. ttl=60
Done. 1 corrections.
```

The same binary without diff2

```

/dnscontrol -v preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test --diff2 as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
Ignoring record @ R53_ALIAS due to IGNORE_NAME
Ignoring record _9REDACTED CNAME due to IGNORE_NAME
Ignoring record _REDACTED CNAME due to IGNORE_TARGET
Ignoring record _ed TXT due to IGNORE_NAME
Ignoring record _REDACTED CNAME due to IGNORE_TARGET
Ignoring record REDACTED R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.REDACTED TXT due to IGNORE_NAME
Ignoring record _ed.cname-REDACTED TXT due to IGNORE_NAME
Ignoring record _ed.cname-gift TXT due to IGNORE_NAME
Ignoring record _ed.cname-www TXT due to IGNORE_NAME
Ignoring record gift R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.gift TXT due to IGNORE_NAME
Ignoring record rules R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.rules TXT due to IGNORE_NAME
Ignoring record www R53_ALIAS due to IGNORE_NAME
Ignoring record _ed.www TXT due to IGNORE_NAME
Done. 0 corrections.
```

**Comment by tlimoncelli** [comment]
I found it!

In diff2, IGNORE_TARGET was comparing against the label instead of the target!

Here's the fix:

```
                if matchLabel(uc.LabelGlob, rec.GetLabel()) &&
                        matchType(uc.RTypeMap, rec.Type) &&
-                       matchTarget(uc.TargetGlob, rec.GetLabel()) {
+                       matchTarget(uc.TargetGlob, rec.GetTargetField()) {
                        return true
```

To find the problem, all I had to do was build a new test framework!  (Just kidding... I just added 1 new function)

PR is here: https://github.com/StackExchange/dnscontrol/pull/2338

Please test it:

```
git clone https://github.com/StackExchange/dnscontrol.git
cd dnscontrol
git checkout tlim_b2285_r53_alias
go install
```

(It might be merged to master soon)

**Comment by tlimoncelli** [comment]
(Re-opening this bug until bugfix is confirmed by @JBOClara )

**Comment by JBOClara** [comment]
Thanks, I'll test this as soon as possible.

Thanks @tlimoncelli 🙏

**Comment by JBOClara** [comment]
With the master version, test with diff2:

````
dnscontrol -v --diff2 preview --domains "domain.co.uk"
[INFO: Diff2 algorithm in use.]
******************** Domain: domain.co.uk
1 correction (r53)
#1: INFO: 20 records not being deleted because of IGNORE*():
    domain.co.uk. R53_ALIAS k8s-sharedisingress-137dd98d08-677527462.us-east-1.elb.amazonaws.com. atype=A zone_id=YYYYY
    _XXXX.domain.co.uk. CNAME _XXXX.YYYY.acm-validations.aws.
    _XXXX.domain.co.uk. CNAME _XXXX.YYYY.acm-validations.aws.
    _XXXX.domain.co.uk. TXT "heritage=external-dns,external-dns/owner=eks-customer-prod-cluster,external-dns/resource=ingress/default/ingress"
    _XXXX.domain.co.uk. CNAME _XXXXX.YYYY.acm-validations.aws.
    ...and 15 more... (use --full to show all)
Done. 1 corrections.
```

and without diff2:
```
dnscontrol  preview --domains "domain.co.uk"
[INFO: Old diff algorithm in use. Please test `dnscontrol --diff2 preview` (or push) as it will be the default in releases after 2023-05-07. See https://github.com/StackExchange/dnscontrol/issues/2262]
******************** Domain: domain.co.uk
Done. 0 corrections.
```

**Comment by tlimoncelli** [comment]
Ah, yes, this is something that will be fixed before diff2 becomes the default.

diff1 doesn't report what got ignored.  I don't plan on fixing this.

diff2 reports the "INFO" changes as "changes", which means the count is off.  My plan is to fix this before diff2 becomes the default. See https://github.com/StackExchange/dnscontrol/issues/2300

**Comment by tlimoncelli** [comment]
P.S. I didn't get a lot of sleep last night.  Please verify that I understood your comment correctly.

**Comment by JBOClara** [comment]
Thanks @tlimoncelli 

This issue can be close
