### ISSUE TITLE
get-zones : panic: short (domain.tld) is not supposed to end with a dot

### ISSUE THREAD

**Issue by matclab** [StackExchange/dnscontrol#2865]
**Describe the bug**
I got an exception when trying to get zone from an existing domain

**To Reproduce**
Run 
```
dnscontrol get-zones --format=djs ovh OVH lost.re
```
I then get 
```
WARNING: To retain compatibility in future versions, please change "OVH" to "-". See "https://docs.dnscontrol.org/commands/get-zones"
panic: short (lost.re) is not supposed to end with a dot

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v4/models.(*RecordConfig).SetLabel(0xc000cbac80, {0xc000c481e0, 0x29}, {0x7ffc689da7e4, 0x7})
	/home/runner/work/dnscontrol/dnscontrol/models/record.go:254 +0x22e
github.com/StackExchange/dnscontrol/v4/providers/ovh.nativeToRecord(0xc000976e10, {0x7ffc689da7e4, 0x7})
	/home/runner/work/dnscontrol/dnscontrol/providers/ovh/ovhProvider.go:216 +0xfd
github.com/StackExchange/dnscontrol/v4/providers/ovh.(*ovhProvider).GetZoneRecords(0xc0008f8450, {0x7ffc689da7e4, 0x7}, 0x0?)
	/home/runner/work/dnscontrol/dnscontrol/providers/ovh/ovhProvider.go:125 +0x12e
github.com/StackExchange/dnscontrol/v4/commands.GetZone({{{0x1a652b4, 0xa}}, {0x7ffc689da7dc, 0x3}, {0x7ffc689da7e0, 0x3}, {0xc0008e87d0, 0x1, 0x1}, {0x7ffc689da7d8, ...}, ...})
	/home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:203 +0x587
github.com/StackExchange/dnscontrol/v4/commands.glob..func5.1(0xc0008e7e40)
	/home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:40 +0x2a5
github.com/urfave/cli/v2.(*Command).Run(0xc0000f58c0, 0xc0008e7e40, {0xc000773f40, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0xc00085a580, 0xc0008e7c40, {0xc0001ae120, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc000858600, {0x1d0c078?, 0x28347e0}, {0xc0001ae120, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/StackExchange/dnscontrol/v4/commands.Run({0xc0001c10f8?, 0x1a74e85?})
	/home/runner/work/dnscontrol/dnscontrol/commands/commands.go:104 +0x43b
main.main()
	/home/runner/work/dnscontrol/dnscontrol/main.go:30 +0xad
```
**Expected behavior**
I expect a dnsconfig.js like file without exception.

**DNS Provider**
 - OVH
 - 
**Additional context**
NA

**Comment by matclab** [comment]
Obtained with dnscontrol 4.8.2

**Comment by tlimoncelli** [comment]
CC @masterzen (OVH provider maintainer)

**Comment by masterzen** [comment]
@matclab thanks for the report, it chokes on a name in the `lost.re` zone that seems to end up with a `.` which shouldn't be possible.
Would you mind listing all records in that zone so that we can identify the exact format of that label?
I can add protection code for sure (and will do), but I would prefer understanding the root issue.

**Comment by masterzen** [comment]
Forgot to say, that with HEAD, I have no issue using `get-zones` on my own zones.

**Comment by matclab** [comment]
Oh You're right… I've overlooked the following config line:
```
xxxxxxxxxxxxxxxxxxxx.lostre. IN CNAME verify.bing.com.
```

Removing the spurious `lost.re.` solved the problem. Sorry for not having spotted the problem before and adding some more noise to this universe :-/

**Comment by masterzen** [comment]
Well, maybe we can have an error message that is more explicit, because if OVH allows to setup such labels, we need to error gracefully, not panic . I'll think about it :)
