### ISSUE TITLE
Using ALIAS with DNSimple causes panic

### ISSUE THREAD

**Issue by onlyhavecans** [StackExchange/dnscontrol#321]
I just updated tonight and now using an ALIAS causes a panic.
I manually rolled back to v0.2.5 and the issue is not present. It seems to be caused by the recent refactor.

```
> dnscontrol preview
******************** Domain: exploration5.games
----- Getting nameservers from: xxx
----- DNS Provider: xxx...panic: unparsable record received from dnsimple: Unknown rtype (ALIAS) when parsing (critic-whistles-17050.netlify.com.) domain=(exploration5.games)

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/dnsimple.(*DnsimpleApi).GetDomainCorrections(0xc4204e2960, 0xc4202c4960, 0x14, 0xc4202c4900, 0x1, 0x0, 0x1)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/providers/dnsimple/dnsimpleProvider.go:93 +0xfc3
github.com/StackExchange/dnscontrol/commands.run(0x1939895, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1937f3e, 0xa, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3ce
github.com/StackExchange/dnscontrol/commands.Preview(0x1939895, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1937f3e, 0xa, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc42025c160, 0x0, 0xc42025c160)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x179a6c0, 0xc420166010, 0xc42025c160, 0xc4201ca800, 0x0)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1935889, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x195a2e9, 0x4e, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc42022a340, 0xc42000c080, 0x2, 0x2, 0x0, 0x0)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:255 +0x6a0
github.com/StackExchange/dnscontrol/commands.Run(0xc4201cea00, 0x14, 0xc42008a058)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by tlimoncelli** [comment]
I don't have a test account on dnsimple, but the code I just submitted should fix the issue. I hope ;-).  Please test it and let me know.

**Comment by onlyhavecans** [comment]
This fixes the issue with crashing on ALIAS! 👍

**Comment by onlyhavecans** [comment]
Also, sandbox accounts are free if you would like!
