### ISSUE TITLE
Having a URL record in DNSimple account causes crash

### ISSUE THREAD

**Issue by onlyhavecans** [StackExchange/dnscontrol#324]
In master when I run a preview on a domain that has a URL record in it dnscontrol crashes now. This behavior is new after the refactor.

```
~/go/bin/dnscontrol preview
******************** Domain: blueoxtavern.com
----- Getting nameservers from: xxx
----- DNS Provider: xxx...panic: unparsable record received from dnsimple: Unknown rtype (URL) when parsing (https://apps.vdomobile.com/m/blueoxtavernlv/?appcode=blueoxtavernlv) domain=(blueoxtavern.com)

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/dnsimple.(*DnsimpleApi).GetDomainCorrections(0xc420502cc0, 0xc420483b80, 0x14, 0xc420483b00, 0x1, 0x0, 0x1)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/providers/dnsimple/dnsimpleProvider.go:96 +0x106b
github.com/StackExchange/dnscontrol/commands.run(0x1939935, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1937fde, 0xa, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3ce
github.com/StackExchange/dnscontrol/commands.Preview(0x1939935, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1937fde, 0xa, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc42028c160, 0x0, 0xc42028c160)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x179a760, 0xc420190010, 0xc42028c160, 0xc4201ba900, 0x0)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1935929, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x195a389, 0x4e, 0x0, ...)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc42025a340, 0xc4200be000, 0x2, 0x2, 0x0, 0x0)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:255 +0x6a0
github.com/StackExchange/dnscontrol/commands.Run(0xc4201e8a20, 0x14, 0xc420098058)
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/dos/go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
make: *** [build] Error 2
```

Here is the appropiate record in my config

```
D('blueoxtavern.com', REG_NONE, DnsProvider(DNSIMPLE),
  IGNORE('@'),
  IGNORE('*')
)
```

**Comment by tlimoncelli** [comment]
Does this branch fix it?

https://github.com/StackExchange/dnscontrol/pull/325
https://github.com/StackExchange/dnscontrol/tree/dnsimpleurl

**Comment by onlyhavecans** [comment]
👍  
Yep! Checking out and building that branch fixed this error

```
2018/02/27 12:44:35 diff.go:79: Ignoring record blueoxtavern.com URL due to IGNORE
2018/02/27 12:44:35 diff.go:79: Ignoring record *.blueoxtavern.com URL due to IGNORE
0 corrections
```

**Comment by tlimoncelli** [comment]
awesome!

**Comment by tlimoncelli** [comment]
Merged https://github.com/StackExchange/dnscontrol/pull/325
