### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by domelu** [StackExchange/dnscontrol#329]
## JS
var registrar = NewRegistrar('none', 'NONE');
var DNS_R53 = NewDnsProvider("r53", "ROUTE53");

D('example.com', registrar, DnsProvider(DNS_R53),
IGNORE('test')
)

## GO version
Binary from https://github.com/StackExchange/dnscontrol/releases/download/v0.2.5/dnscontrol-Linux

## python -m json.tool creds.json
{
    "bind": {},
    "bind_internal": {},
    "r53": {
        "KeyId": "xxx",
        "SecretKey": "xxx"
    }
}

## Route53 zone type
public

## Comments
test.example.com = "Traffic policy record" (CNAME)

## CLI
dnscontrol-Linux preview -creds creds.json --js example.com.js

## Result
Initialized 1 registrars and 1 dns service providers.
******************** Domain: example.com
----- Getting nameservers from: r53
----- DNS Provider: r53...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xabb265]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/route53.(*route53Provider).GetDomainCorrections(0xc4203ea360, 0xc42009a080, 0xc4204a2fea, 0x3, 0xc420282748, 0x1, 0x0)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:168 +0x275
github.com/StackExchange/dnscontrol/commands.run(0x7ffdb322d89b, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffdb322d88b, 0xa, 0x0, ...)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:133 +0x5f1
github.com/StackExchange/dnscontrol/commands.Preview(0x7ffdb322d89b, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffdb322d88b, 0xa, 0x0, ...)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:80 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc420084dc0, 0x100, 0xc420084dc0)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:24 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0xbf53c0, 0xc420045f30, 0xc420084dc0, 0xc420011800, 0x0)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0xd88148, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdabb04, 0x4e, 0x0, ...)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4201c5860, 0xc4200100c0, 0x6, 0x6, 0x0, 0x0)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:255 +0x6f8
github.com/StackExchange/dnscontrol/commands.Run(0xc42006a600, 0x57, 0xb39812)
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/commands.go:49 +0x18a
main.main()
	/home/tlimoncelli/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34

**Comment by tlimoncelli** [comment]
I'm having trouble reproducing this panic:

```
$ ./dnscontrol-Darwin preview
Initialized 1 registrars and 1 dns service providers.
******************** Domain: dnscontroltest-r53.com
----- Getting nameservers from: r53
----- DNS Provider: r53...1 correction
#1: DELETE NS dnscontroltest-r53.com ns1.otherdomain.tld. ttl=300
DELETE NS dnscontroltest-r53.com ns2.otherdomain.tld. ttl=300

----- Registrar: none...0 corrections
Done. 1 corrections.
$ cat dnsconfig.js       
var registrar = NewRegistrar('none', 'NONE');
var DNS_R53 = NewDnsProvider("r53", "ROUTE53");

D('dnscontroltest-r53.com', registrar, DnsProvider(DNS_R53),
  IGNORE('test')
)
$ cat creds.json 
{
  "bind": {},
  "bind_internal": {},
  "r53": {
    "KeyId": "xyz",
    "SecretKey": "xyz"
  }
}
$ 
```

Can you help me reproduce the issue?

Also... could you try building the binary from "master" and see if that has the same problem?

**Comment by domelu** [comment]
Same with "master". Did you create traffic flow policy record in dnscontroltest-r53.com? https://aws.amazon.com/blogs/aws/new-route-53-traffic-flow/

```
./dnscontrol preview -creds creds.json --js example.com.js
******************** Domain: gog.tv
----- Getting nameservers from: r53
----- DNS Provider: r53...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b1990]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/route53.nativeToRecords(0xc4201c6500, 0xc4204b2dc0, 0x6, 0x0, 0x1f100e0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:296 +0xf0
github.com/StackExchange/dnscontrol/providers/route53.(*route53Provider).GetDomainCorrections(0xc420350d20, 0xc42035b040, 0x3, 0xc42035b000, 0x1, 0x0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:158 +0x1fe
github.com/StackExchange/dnscontrol/commands.run(0x7ffeefbff78c, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff77c, 0xa, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3ce
github.com/StackExchange/dnscontrol/commands.Preview(0x7ffeefbff78c, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff77c, 0xa, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc420278160, 0xc4201d8900, 0xc420278160)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x17e5700, 0xc42016a020, 0xc420278160, 0x0, 0xc4201d8960)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1987aec, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ae22d, 0x4e, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4201fc1c0, 0xc42001e0c0, 0x6, 0x6, 0x0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x6e8
github.com/StackExchange/dnscontrol/commands.Run(0xc4201dcaa0, 0x14, 0xc42002e0b8)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by tlimoncelli** [comment]
sadly I don't know enough about AWS to know what a traffic flow policy record is :-(.  If you walk me through setting that up, that'd be great. However, I think I see the problem.

Thanks to your most recent panic output, it looks like the problem is with *set.TTL.  Could you add this debug statement?

```
$ git diff
diff --git a/providers/route53/route53Provider.go b/providers/route53/route53Provider.go
index b7b386d..5c87cd4 100644
--- a/providers/route53/route53Provider.go
+++ b/providers/route53/route53Provider.go
@@ -293,6 +293,7 @@ func nativeToRecords(set *r53.ResourceRecordSet, origin string) []*models.Record
                        case "SOA":
                                continue
                        default:
+                               fmt.Printf("DEBUG: TTL=%v\n", set.TTL)
                                rc := &models.RecordConfig{TTL: uint32(*set.TTL)}
                                rc.SetLabelFromFQDN(unescape(set.Name), origin)
                                if err := rc.PopulateFromString(*set.Type, *rec.Value, origin); err != nil {
```

**Comment by domelu** [comment]
## Traffic policy

similar problem:
- https://github.com/barnybug/cli53/issues/148
- https://github.com/barnybug/cli53/pull/152/files

I think, dnscontrol should skip traffic policy records

## Debug
```
./dnscontrol preview -creds creds.json --js example.com.js
******************** Domain: example.com
----- Getting nameservers from: r53
----- DNS Provider: r53...DEBUG: RTYPE=NS TTL=0xc420229840 REC={
  Value: "ns-349.awsdns-43.com."
}
DEBUG: RTYPE=NS TTL=0xc420229840 REC={
  Value: "ns-1111.awsdns-10.org."
}
DEBUG: RTYPE=NS TTL=0xc420229840 REC={
  Value: "ns-891.awsdns-47.net."
}
DEBUG: RTYPE=NS TTL=0xc420229840 REC={
  Value: "ns-1764.awsdns-28.co.uk."
}
DEBUG: RTYPE=CNAME TTL=<nil> REC={
  Value: "This resource record set includes an attribute that is unsupported on this Route 53 endpoint. Please consider using a newer endpoint or a tool that does so."
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b1a69]

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/route53.nativeToRecords(0xc4200ee780, 0xc420229110, 0x6, 0x0, 0x1f100e0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:297 +0x1c9
github.com/StackExchange/dnscontrol/providers/route53.(*route53Provider).GetDomainCorrections(0xc420496d80, 0xc420317720, 0x3, 0xc420317700, 0x1, 0x0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/providers/route53/route53Provider.go:158 +0x1fe
github.com/StackExchange/dnscontrol/commands.run(0x7ffeefbff754, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff744, 0xa, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3ce
github.com/StackExchange/dnscontrol/commands.Preview(0x7ffeefbff754, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff744, 0xa, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc420284160, 0xc4201ae900, 0xc420284160)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x17e57e0, 0xc420182020, 0xc420284160, 0x0, 0xc4201ae9c0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1987bcc, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ae32b, 0x4e, 0x0, ...)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4202061c0, 0xc4200b6000, 0x6, 0x6, 0x0, 0x0)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x6e8
github.com/StackExchange/dnscontrol/commands.Run(0xc4201ccae0, 0x14, 0xc42008c058)
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/domelu/go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by domelu** [comment]
My PR https://github.com/StackExchange/dnscontrol/pull/330
