### ISSUE TITLE
BIND CNAME causes panic on push

### ISSUE THREAD

**Issue by necrogami** [StackExchange/dnscontrol#344]
Looking in providers/bind/prettyzone.go there appears to be no handler for CNAME records in bind and it throws a panic

```necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol preview
******************** Domain: c4.io
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: c4.io
CREATE NS c4.io c4.io ttl=300
CREATE NS c4.io c4.io ttl=300
CREATE SOA c4.io ns1.c4.io. a.c4.io. 1 21600 3600 604800 120 ttl=0
CREATE A  104.131.176.127 ttl=300
CREATE A  159.203.172.64 ttl=300
CREATE AAAA  2604:a880:800:10::2990:a001 ttl=300
CREATE AAAA  2604:a880:800:a1::92b:5001 ttl=300
CREATE MX  1 aspmx.l.google.com. ttl=300
CREATE MX  5 alt1.aspmx.l.google.com. ttl=300
CREATE MX  5 alt2.aspmx.l.google.com. ttl=300
CREATE MX  10 alt3.aspmx.l.google.com. ttl=300
CREATE MX  10 alt4.aspmx.l.google.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300

----- Registrar: none...0 corrections
Done. 1 corrections.

necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol push
******************** Domain: c4.io
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: c4.io
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE NS c4.io c4.io ttl=300
CREATE NS c4.io c4.io ttl=300
CREATE SOA c4.io ns1.c4.io. a.c4.io. 1 21600 3600 604800 120 ttl=0
CREATE A  104.131.176.127 ttl=300
CREATE A  159.203.172.64 ttl=300
CREATE AAAA  2604:a880:800:10::2990:a001 ttl=300
CREATE AAAA  2604:a880:800:a1::92b:5001 ttl=300
CREATE MX  1 aspmx.l.google.com. ttl=300
CREATE MX  5 alt1.aspmx.l.google.com. ttl=300
CREATE MX  5 alt2.aspmx.l.google.com. ttl=300
CREATE MX  10 alt3.aspmx.l.google.com. ttl=300
CREATE MX  10 alt4.aspmx.l.google.com. ttl=300

CREATING ZONEFILE: zones/c4.io.zone
panic: zoneGenData Less: unimplemented rtype CNAME

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/bind.(*zoneGenData).Less(0xc4205502a0, 0x2, 0x1, 0x1)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/bind/prettyzone.go:95 +0xfee
sort.insertionSort(0x1f42d00, 0xc4205502a0, 0x0, 0x9)
	/usr/local/Cellar/go/1.9.2/libexec/src/sort/sort.go:29 +0x9c
sort.quickSort(0x1f42d00, 0xc4205502a0, 0x0, 0x9, 0x7)
	/usr/local/Cellar/go/1.9.2/libexec/src/sort/sort.go:211 +0x207
sort.Sort(0x1f42d00, 0xc4205502a0)
	/usr/local/Cellar/go/1.9.2/libexec/src/sort/sort.go:220 +0x79
github.com/StackExchange/dnscontrol/providers/bind.(*zoneGenData).generateZoneFileHelper(0xc4205502a0, 0x1f3d080, 0xc42000e120, 0x8, 0x9)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/bind/prettyzone.go:163 +0x4f
github.com/StackExchange/dnscontrol/providers/bind.WriteZoneFile(0x1f3d080, 0xc42000e120, 0xc42009a000, 0xf, 0xf, 0xc420183c90, 0x5, 0x0, 0x8)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/bind/prettyzone.go:155 +0x2ae
github.com/StackExchange/dnscontrol/providers/bind.(*Bind).GetDomainCorrections.func1(0x1fc0108, 0x0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/bind/bindProvider.go:296 +0x361
github.com/StackExchange/dnscontrol/commands.printOrRunCorrections(0xc4201823d8, 0x5, 0xc4201823d4, 0x4, 0xc42000e110, 0x1, 0x1, 0x1f49700, 0x1fc0108, 0x1, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:235 +0xda
github.com/StackExchange/dnscontrol/commands.run(0x19f4831, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19f2e5a, 0xa, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:136 +0x4f6
github.com/StackExchange/dnscontrol/commands.Push(0x19f4831, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19f2e5a, 0xa, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:86 +0x7e
github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc420238160, 0x0, 0xc420238160)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:57 +0x5b
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x1852ce0, 0xc42014e020, 0xc420238160, 0x0, 0xc4201a0960)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x19ed6c7, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a0ec55, 0x2d, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4201c41c0, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x740
github.com/StackExchange/dnscontrol/commands.Run(0xc420188ac0, 0x14, 0x1791122)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34

necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol version
dnscontrol 0.2.6-dev
```

**Comment by tlimoncelli** [comment]
Does https://github.com/StackExchange/dnscontrol/pull/347 fix this?

I'm surprised this panic didn't happen in our integration testing or unit tests.  I've made the code more robust and added some tests to help catch this kind of thing in the future.

**Comment by tlimoncelli** [comment]
This is now fixed.

**Comment by tIimonceIIi** [comment]
You are such a piece of junk. Always trying to crash dnscontrol.

**Comment by tlimoncelli** [comment]
I didn't write that. I think my account was hacked.
