### ISSUE TITLE
Missing hosts bind provider

### ISSUE THREAD

**Issue by necrogami** [StackExchange/dnscontrol#348]
So i applied the patch from the https://github.com/StackExchange/dnscontrol/pull/347 After passing the bug it was fixing i generated my bind file and now i'm missing all my hosts. So instead of 
`mail                 IN CNAME ghs.googlehosted.com.`
It's showing 
`                 IN CNAME ghs.googlehosted.com.`

dnsconfig.js
```
// Providers:

var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var BIND = NewDnsProvider('bind', 'BIND', {     // ISC BIND.
        'default_soa': {
        'master': 'ns1.c4.io.',
        'mbox': 'a.c4.io.',
        'refresh': 21600,
        'retry': 3600,
        'expire': 604800,
        'minttl': 120,
    }
})  


// Domains:

D('c4.io', REG_NONE, DnsProvider(BIND),
    NAMESERVER("@", "ns1.c4.io."),
    NAMESERVER("@", "ns2.c4.io."),
    A("ns1", "104.131.176.127"),
    A("ns2", "159.203.172.64"),
    AAAA("ns1", "2604:a880:800:10::2990:a001"),
    AAAA("ns2", "2604:a880:800:a1::92b:5001"),
    MX('@', 1, 'aspmx.l.google.com.'),
    MX('@', 5, 'alt1.aspmx.l.google.com.'),
    MX('@', 5, 'alt2.aspmx.l.google.com.'),
    MX('@', 10, 'alt3.aspmx.l.google.com.'),
    MX('@', 10, 'alt4.aspmx.l.google.com.'),
    CNAME('calendar', 'ghs.googlehosted.com.'),
    CNAME('docs', 'ghs.googlehosted.com.'),
    CNAME('mail', 'ghs.googlehosted.com.')
);
```

console from writing file
```necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol push
******************** Domain: c4.io
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: c4.io
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE CNAME  ghs.googlehosted.com. ttl=300
CREATE NS c4.io c4.io ttl=300
CREATE NS c4.io c4.io ttl=300
CREATE SOA c4.io ns1.c4.io. a.c4.io. 1 21600 3600 604800 120 ttl=0
CREATE A  104.131.176.127 ttl=300
CREATE A  159.203.172.64 ttl=300
CREATE AAAA  2604:a880:800:10::2990:a001 ttl=300
CREATE AAAA  2604:a880:800:a1::92b:5001 ttl=300
CREATE MX  1 aspmx.l.google.com. ttl=300
CREATE MX  5 alt1.aspmx.l.google.com. ttl=300
CREATE MX  5 alt2.aspmx.l.google.com. ttl=300
CREATE MX  10 alt3.aspmx.l.google.com. ttl=300
CREATE MX  10 alt4.aspmx.l.google.com. ttl=300

CREATING ZONEFILE: zones/c4.io.zone
SUCCESS!
----- Registrar: none...0 corrections
Done. 1 corrections.
```
output of zone file missing all hosts
```necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4/zones
$ cat c4.io.zone 
$TTL 300
.                IN A     104.131.176.127
                 IN A     159.203.172.64
                 IN CNAME ghs.googlehosted.com.
                 IN CNAME ghs.googlehosted.com.
                 IN CNAME ghs.googlehosted.com.
                 IN MX    1 aspmx.l.google.com.
                 IN MX    5 alt1.aspmx.l.google.com.
                 IN MX    5 alt2.aspmx.l.google.com.
                 IN MX    10 alt3.aspmx.l.google.com.
                 IN MX    10 alt4.aspmx.l.google.com.
                 IN AAAA  2604:a880:800:10::2990:a001
                 IN AAAA  2604:a880:800:a1::92b:5001
@                IN SOA   ns1.c4.io. a.c4.io. 1 21600 3600 604800 120
                 IN NS    c4.io
                 IN NS    c4.io

```

**Comment by tlimoncelli** [comment]
The problem here is that `NAMESERVER()` only takes 1 argument and the test case has 2.  Unlike NS(), you don't need to specify a label because NAMESERVER() only applies to the current domain.

We've updated the docs, changed NAMESERVER() to fail if >1 args are passed.

FYI: Previously this function took a 2nd parameter... an IP address. However that IP was never used.

If you build new binaries from the master branch, and change your NAMESERVER() statements, this should work now.

You may need to delete any *.zone files that were generated as they may be invalid.

**Comment by necrogami** [comment]
After pulling the latest changes and rebuilding here's what happens (before and after the nameserver change to single value (removing the "@",))

```
necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol push
Executing javascript in dnsconfig.js: NAMESERVER only accepts one argument for name.

necrogami at Antons-MacBook-Pro-2 in ~/Downloads/dns/io/c4
$ dnscontrol push
******************** Domain: c4.io
----- Getting nameservers from: bind
----- DNS Provider: bind...panic: DUPLICATE E_RECORD FOUND: { CNAME} ghs.googlehosted.com. ttl=300

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/diff.(*differ).IncrementalDiff(0xc420439fc0, 0xc4202b4000, 0xf, 0x10, 0x1f40040, 0xc420439fc0, 0xe, 0x1c, 0x1, 0xc42045bdca, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/diff/diff.go:130 +0x277b
github.com/StackExchange/dnscontrol/providers/bind.(*Bind).GetDomainCorrections(0xc420357980, 0xc42036a6e0, 0x4, 0xc42036a600, 0x1, 0x0, 0x0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/providers/bind/bindProvider.go:253 +0x976
github.com/StackExchange/dnscontrol/commands.run(0x19f4631, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19f2c5a, 0xa, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3d7
github.com/StackExchange/dnscontrol/commands.Push(0x19f4631, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19f2c5a, 0xa, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:86 +0x7e
github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc420098dc0, 0x0, 0xc420098dc0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:57 +0x5b
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x1852b00, 0xc42014e020, 0xc420098dc0, 0x0, 0xc4201e62a0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xd2
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x19ed4c7, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a0ea2d, 0x2d, 0x0, ...)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc420124700, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x740
github.com/StackExchange/dnscontrol/commands.Run(0xc420013480, 0x14, 0x1790f62)
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
main.main()
	/Users/necrogami/code/gocode/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by tlimoncelli** [comment]
Try deleting the zones/c4.io.zone file.  It probably has been corrupted.

**Comment by necrogami** [comment]
This is fixed.
