### ISSUE TITLE
Issue with latest Docker image

### ISSUE THREAD

**Issue by kjacobsen** [StackExchange/dnscontrol#371]
Hi,

I have noticed some issues with CloudFlare and the latest Docker image. ```docker run --rm -it stackexchange/dnscontrol dnscontrol version``` it returns version 0.2.6 with a build date of 25 jun 2018. 

When I run: ```docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol dnscontrol preview``` with my configuration, get a panic:

```
2018-07-07T14:29:36.7387550Z [command]/usr/local/bin/docker run --rm -v /opt/vsts/work/1/a/dns/dnsconfig.js:/dns/dnsconfig.js -v /opt/vsts/work/1/a/dns/creds.json:/dns/creds.json stackexchange/dnscontrol dnscontrol preview
2018-07-07T14:29:36.7410734Z 1 Validation errors:
2018-07-07T14:29:36.7429223Z WARNING: 3 spf record lookups are out of date with cache (spf.protection.outlook.com,spfa.protection.outlook.com,spfb.protection.outlook.com).
2018-07-07T14:29:36.7445559Z Wrote changes to spfcache.updated.json. Please rename and commit:
2018-07-07T14:29:36.7460442Z     $ mv spfcache.updated.json spfcache.json
2018-07-07T14:29:36.7474655Z     $ git commit spfcache.json
2018-07-07T14:29:36.7490363Z ******************** Domain: planetpowershell.com
2018-07-07T14:29:36.7505358Z ----- Getting nameservers from: cloudflare.com
2018-07-07T14:29:36.7527119Z ----- DNS Provider: cloudflare.com...panic: error decoding priority from cloudflare record: strconv.ParseInt: parsing "": invalid syntax
2018-07-07T14:29:36.7536233Z 
2018-07-07T14:29:36.7550427Z goroutine 1 [running]:
2018-07-07T14:29:36.7592725Z github.com/StackExchange/dnscontrol/providers/cloudflare.(*cfRecord).nativeToRecord(0xc4206249c0, 0xc420528860, 0x14, 0xc420546fa0)
2018-07-07T14:29:36.7607933Z 	/go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:389 +0x790
2018-07-07T14:29:36.7621706Z github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).getRecordsForDomain(0xc420096c40, 0xc4205b7de0, 0x20, 0xc420528860, 0x14, 0x493301, 0xc420068050, 0xc42008b3c0, 0x25, 0x40)
2018-07-07T14:29:36.7643074Z 	/go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/rest.go:70 +0x19e
2018-07-07T14:29:36.7664757Z github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).GetDomainCorrections(0xc420096c40, 0xc4201380a0, 0xe, 0xc420138000, 0x1, 0x0, 0x0)
2018-07-07T14:29:36.7687596Z 	/go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:101 +0x117
2018-07-07T14:29:36.7702905Z github.com/StackExchange/dnscontrol/commands.run(0xe89d76, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe882b8, 0xa, 0x0, ...)
2018-07-07T14:29:36.7717917Z 	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3d7
2018-07-07T14:29:36.7731484Z github.com/StackExchange/dnscontrol/commands.Preview(0xe89d76, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe882b8, 0xa, 0x0, ...)
2018-07-07T14:29:36.7746091Z 	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
2018-07-07T14:29:36.7762159Z github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc420084f20, 0x0, 0xc420084f20)
2018-07-07T14:29:36.7778312Z 	/go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
2018-07-07T14:29:36.7794941Z github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0xcd5180, 0xc420136050, 0xc420084f20, 0x0, 0xc420172900)
2018-07-07T14:29:36.7812047Z 	/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xd2
2018-07-07T14:29:36.7828712Z github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0xe85a30, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xeae3a9, 0x4e, 0x0, ...)
2018-07-07T14:29:36.7845161Z 	/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x4bb
2018-07-07T14:29:36.7859226Z github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc42010c8c0, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
2018-07-07T14:29:36.7873498Z 	/go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x740
2018-07-07T14:29:36.7895277Z github.com/StackExchange/dnscontrol/commands.Run(0xc420060660, 0x5e, 0xc09032)
2018-07-07T14:29:36.7911013Z 	/go/src/github.com/StackExchange/dnscontrol/commands/commands.go:50 +0x18a
2018-07-07T14:29:36.7923494Z main.main()
2018-07-07T14:29:36.7937975Z 	/go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

I noticed on Docker Hub that the ```latest``` tagged Docker image is 8mb, but the ```v0.2.6``` tagged is 7mb.

Running the following command results in no errors: ```docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol:v0.2.6 dnscontrol preview```

Do we know what/why the new docker file was built on 25-06-2018? It certainly doesn't match any of the GitHub releases.

**Comment by kjacobsen** [comment]
Just took a look at any previously merged pull requests. PR #369 was merged in 12 days ago, and #368 was merged in 15 days ago. #368 actually impacts CloudFlare behavior. Worth noting that both PRs failed their branch Travis CI builds.

**Comment by captncraig** [comment]
I'll admit, I'm a little stumped. 

1. The `latest` tag on docker hub is in fact built properly from master.
2. The stack trace makes me pretty sure this is not a problem with the container image, but the code itself.
3. All integration tests on cloudflare pass for me on master.
4. You still appear to be getting api responses that have empty string for MX record priorities.

Can you check your cloudflare account in the ui and see if anything looks off about any mx records? Another possibility is our unmarshalling code is off somehow, or different accounts get different formats or something.

**Comment by kjacobsen** [comment]
I am just as stumped.

When I use the ```latest``` tag on Docker hub, it reports 0.2.6, but I get errors back from CloudFlare. If I switch to the ```0.2.6``` tag, everything is fine.

Just to confirm, is the ```latest``` tag on Docker based upon master as it stands now or 0.2.6 as it reports its version as?

**Comment by kjacobsen** [comment]
Spent some more time testing. It was as I started to suspect.

If the MX priority is 0, then the casting fails. I haven't dug into it, but I suspect when the priority is 0, CloudFlare returns an empty string and that causes the parsing error as seen in ```[error]panic: error decoding priority from cloudflare record: strconv.ParseInt: parsing "": invalid syntax```.

I will put together a PR to add some logic for handling empty strings correctly.

**Comment by tlimoncelli** [comment]
Thanks for debugging that. I don't personally use the container, so I wasn't sure where to start with this.   Did #374 fix the problem?

**Comment by captncraig** [comment]
The latest tag is automatically built from master. Individual release tags are created automatically anytime we tag a definite release, but that seems to happen a bit irregularly.

**Comment by kjacobsen** [comment]
Hi

All fixed, and the logic around the Docker container makes sense.
