### ISSUE TITLE
CloudFlare SPF record

### ISSUE THREAD

**Issue by srfraser** [StackExchange/dnscontrol#446]
In a similar manner to #339, CloudFlare returns an SPF record, which crashes dnscontrol.

```******************** Domain: mydomain.org
----- Getting nameservers from: cloudflare
----- DNS Provider: cloudflare...panic: unparsable record received from cloudflare: Unknown rtype (SPF) when parsing (v=spf1 include:_spf.protonmail.ch mx ~all) domain=(mydomain.org)

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/cloudflare.(*cfRecord).nativeToRecord(0xc4205e4480, 0xc42060ecb0, 0xb, 0xc42061d360)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:419 +0x504
github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).getRecordsForDomain(0xc4202c1a70, 0xc420614220, 0x20, 0xc42060ecb0, 0xb, 0xc42054b601, 0x106d92c, 0x20ca950, 0xc42065a080, 0xc4200d4008)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/cloudflare/rest.go:70 +0x177
github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).GetDomainCorrections(0xc4202c1a70, 0xc42030a140, 0xa, 0xc42030a100, 0x1, 0x0, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:106 +0x117
github.com/StackExchange/dnscontrol/commands.run(0x1ad4140, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ad2519, 0xa, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:129 +0x3ce
github.com/StackExchange/dnscontrol/commands.Preview(0x1ad4140, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ad2519, 0xa, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:81 +0x74
github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc4202e2160, 0xc42023aa00, 0xc4202e2160)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x18feae0, 0xc42019c590, 0xc4202e2160, 0x0, 0xc42023aa80)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1acfbc9, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1afb945, 0x4e, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x47d
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4202621c0, 0xc4200d2020, 0x2, 0x2, 0x0, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x6e8
github.com/StackExchange/dnscontrol/commands.Run(0xc4202dc000, 0x57, 0xc4200ae058)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/commands.go:58 +0x28f
main.main()
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

Should https://github.com/StackExchange/dnscontrol/blob/master/providers/ovh/ovhProvider.go#L162-L164 also be in https://github.com/StackExchange/dnscontrol/blob/master/providers/cloudflare/cloudflareProvider.go#L385 ?

**Comment by tlimoncelli** [comment]
Ah, that brings up an interesting question. Should providers correct mistakes or just warn the user?  Normally bad decisions are detected and warned about in the main code.

I hadn't realized (or I had forgotten) that providers like OVH turn SPF and DKIM records into TXT records.  So, there is a precedent. That said, that's the only provider that does this (I only did a few simple grep's but it seems to be true).

Hmmm...

I'm ok with a solution like https://github.com/StackExchange/dnscontrol/blob/master/providers/ovh/ovhProvider.go#L162-L164 if the documentation provides a clear warning that this will happen.

I'd also be happy with the provider just throwing away those records.  When a provider does that, they will not be deleted because any ignored record is protected by the algorithms (that's how we handle `IGNORE()`. 

Thus, we'll accept a PR either way. Just make sure the docs are updated to reflect the decision. For super extra bonus points, include a link to the bug you've filed with CloudFlare asking them to deprecate SPF.
