### ISSUE TITLE
Unable to run get-certs

### ISSUE THREAD

**Issue by followsound** [StackExchange/dnscontrol#464]
When running `get-certs` I get the following error after dnscontrol tries to clean up a record.

The main issue seems to be with `panic: DUPLICATE D_RECORD FOUND:`

```
2019/04/17 12:08:51 acme.go:93: Checking certificate [bitnest]
2019/04/17 12:08:51 acme.go:106: No existing cert found. Issuing new...
2019/04/17 12:08:52 [INFO] [bitnest.co.uk, www.bitnest.co.uk] acme: Obtaining bundled SAN certificate
2019/04/17 12:08:53 [INFO] [bitnest.co.uk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/<removed>
2019/04/17 12:08:53 [INFO] [www.bitnest.co.uk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/<removed>
2019/04/17 12:08:53 [INFO] [bitnest.co.uk] acme: Could not find solver for: tls-alpn-01
2019/04/17 12:08:53 [INFO] [bitnest.co.uk] acme: Could not find solver for: http-01
2019/04/17 12:08:53 [INFO] [www.bitnest.co.uk] acme: Preparing to solve DNS-01
----- Getting nameservers from: bind
----- Getting nameservers from: digitalocean
[bind] GENERATE_ZONEFILE: bitnest.co.uk
 (15 records)
2019/04/17 12:08:53 [INFO] [bitnest.co.uk] acme: Preparing to solve DNS-01
----- Getting nameservers from: bind
----- Getting nameservers from: digitalocean
2019/04/17 12:08:54 acme.go:287: Cleaning up all records we made
panic: DUPLICATE D_RECORD FOUND: {bitnest.co.uk NS} ns1.digitalocean.com. ttl=300

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/diff.(*differ).IncrementalDiff(0xc00045eac0, 0xc0001955e0, 0xe, 0xe, 0xe, 0xe, 0x0, 0x0, 0xc0007c8cd0, 0xc000222a00, ...)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/providers/diff/diff.go:135 +0x22cb
github.com/StackExchange/dnscontrol/providers/digitalocean.(*DoApi).GetDomainCorrections(0xc0001c4aa0, 0xc000222a00, 0x0, 0x0, 0x23fd600, 0x1, 0x1)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/providers/digitalocean/digitaloceanProvider.go:114 +0x218
github.com/StackExchange/dnscontrol/pkg/acme.getCorrections(0xc000726aa0, 0x2, 0x14, 0x7, 0x8, 0x0)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:253 +0x149
github.com/StackExchange/dnscontrol/pkg/acme.(*certManager).ensureNoPendingCorrections(0xc000172100, 0xc000726aa0, 0x8, 0x8)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:226 +0x40
github.com/StackExchange/dnscontrol/pkg/acme.(*certManager).Present(0xc000172100, 0xc0008ba213, 0xd, 0xc0001bfe30, 0x2b, 0xc00088a3c0, 0x57, 0x0, 0x740000c0003d4470)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:203 +0x41b
github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme.(*dnsChallenge).PreSolve(0xc000402fe0, 0xc0003b61c0, 0x6b, 0xc0008ba260, 0x6, 0xc0008ba266, 0x7, 0xc0001bfe30, 0x2b, 0x0, ...)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme/dns_challenge.go:89 +0x164
github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme.(*Client).solveChallengeForAuthz(0xc0000d80c0, 0xc0000d8240, 0x2, 0x2, 0x0, 0x0)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme/client.go:601 +0x3c5
github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme.(*Client).ObtainCertificate(0xc0000d80c0, 0xc00029c140, 0x2, 0x4, 0xc000402f01, 0x0, 0x0, 0x1, 0xc0002fc870, 0x1, ...)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/xenolf/lego/acme/client.go:434 +0x29d
github.com/StackExchange/dnscontrol/pkg/acme.(*certManager).IssueOrRenewCert.func1(0x0, 0x1b45df0, 0x6)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:102 +0x5e
github.com/StackExchange/dnscontrol/pkg/acme.(*certManager).IssueOrRenewCert(0xc000172100, 0xc0002fc780, 0xf, 0x7ffeefbff801, 0x0, 0x0, 0x0)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/pkg/acme/acme.go:143 +0x528
github.com/StackExchange/dnscontrol/commands.GetCerts(0x1b0eea2, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b0d2b4, 0xa, 0x1b074b9, ...)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/commands/getCerts.go:176 +0x4e0
github.com/StackExchange/dnscontrol/commands.glob..func3.1(0xc000284160, 0xc000030b00, 0xc000284160)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/commands/getCerts.go:23 +0x5b
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0x1942320, 0xc00016e770, 0xc000284160, 0x0, 0xc000030ba0)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0x1b0c57d, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b25d09, 0x24, 0x0, ...)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:165 +0x459
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc00020a1c0, 0xc000096180, 0x6, 0x6, 0x0, 0x0)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:259 +0x6bb
github.com/StackExchange/dnscontrol/commands.Run(0xc000034c00, 0x14, 0xc0000400b8)
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/commands/commands.go:58 +0x271
main.main()
        /Users/samclark/repo/gopath/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34

```

Exact command I'm running is.
```
dnscontrol -v get-certs -email <my_email> --agreeTOS
```

**Comment by tlimoncelli** [comment]
Can you share your (redacted) dnsconfig.js file?  The error
`DUPLICATE D_RECORD FOUND: {bitnest.co.uk NS} ns1.digitalocean.com. ttl=300` means that the diffing algorithm found a situation it can't deal with.

**Comment by followsound** [comment]
Sure, below (let me know if you need more of the redacted stuff, don't really know what to remove!)

```
/*
   dnsconfig.js: dnscontrol configuration file.
*/

// Common things:

require("common.js") # this has repeated stuff like MX records, etc

// Providers:

var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var BIND = NewDnsProvider('bind', 'BIND', {
        'default_soa': {
        'master': 'ns1.digitalocean.com.',
        'mbox': '<redacted>.',
        'refresh': 14400,
        'retry': 3600,
        'expire': 604800,
        'minttl': 1,
    },
    'default_ns': [
        'ns1.digitalocean.com.',
        '<redacted>.'
    ]
    });  // ISC BIND.
var digitalocean = NewDnsProvider('digitalocean', 'DIGITALOCEAN');

DEFAULTS(DnsProvider(digitalocean, 2), DnsProvider(BIND, 2), DefaultTTL(3600));

// Forward domains:
require("domains/bitnest.co.uk.js") // this is the one with the certificate
require("domains/<redacted>.js")
require("domains/<redacted>.js")
require("domains/<redacted>.js")
require("domains/<redacted>.js")

// Reverse domains:
DEFAULTS(DnsProvider(BIND), DefaultTTL(3600));
require("domains/<redacted>.js")
```

**Comment by followsound** [comment]
I should probably add, the DNS provisioning works fine, just `get-certs` that has that error.

**Comment by tlimoncelli** [comment]
Interesting!

The error message indicates that there are exact duplicates of the NS record. Is there a chance that the NS record for ns1.digitalocean.com got in there twice?


CC: @captncraig

**Comment by followsound** [comment]
@tlimoncelli - feel dumb now! There were two entries in DigitalOcean.

However, this hasn't solved the issue as dnscontrol puts two `@ ns1.digitalocean.com` entries back in?

**Comment by followsound** [comment]
Also, just looked and all my domains have two entries for `ns1.digitalocean.com`

```
...
@          300   IN SOA   ns2.crnetworks.net. network.crnetworks.co.uk. 2019041701 14400 3600 604800 1
           300   IN NS    ns1.crnetworks.net.
           300   IN NS    ns1.digitalocean.com.
           300   IN NS    ns1.digitalocean.com.
           300   IN NS    ns2.digitalocean.com.
...
```

**Comment by followsound** [comment]
Sorry for the triple comment, but strangely when I set `DnsProvider(digitalocean, 2)` to `DnsProvider(digitalocean, 0)` I still have an `ns1.digitalocean.com` entry?

**Comment by followsound** [comment]
Fixed, it was a find-replace I had done that had messed up the BIND config.

```
var BIND = NewDnsProvider('bind', 'BIND', {
        'default_soa': {
        'master': 'ns1.crnetworks.net',
        'mbox': 'network.crnetworks.co.uk.',
        'refresh': 14400,
        'retry': 3600,
        'expire': 604800,
        'minttl': 1,
    },
    'default_ns': [
        'ns1.crnetworks.net',
        'ns2.crnetworks.net.'
    ]
    });
```

Apologies for the trouble! Thanks for a fantastic tool!

**Comment by tlimoncelli** [comment]
@followsound I created a branch https://github.com/StackExchange/dnscontrol/tree/validup with better duplicate reporting. Would you have the time to see if you can reproduce your bug with this version and see if the error message is more useful?

**Comment by followsound** [comment]
@tlimoncelli - sure I'll have a go when I get back to my personal machine 👍

**Comment by followsound** [comment]
Apologies for the late reply, work took over and the personal stuff stopped for a month!

The validup branch didn't fix the `panic: DUPLICATE D_RECORD FOUND.`

I also found, if I ran a `push` before the `get-certs` the error disappears.

**Comment by tlimoncelli** [comment]
Does that mean you are no longer blocking on this?

**Comment by followsound** [comment]
@tlimoncelli, yes with the workaround it is no longer blocking.
