### ISSUE TITLE
Panic - index out of range - DigitalOcean

### ISSUE THREAD

**Issue by Silvenga** [StackExchange/dnscontrol#479]
Our DNS changes are stored in git, and a CI server executes every push. Restoring to a know configuration results in the same error. This makes me thing that DigitalOcean may have changed their API. Updating to `v0.2.8` results in the same error.

```
----- Getting nameservers from: digitalocean
----- DNS Provider: digitalocean...panic: runtime error: index out of range

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/models.(*RecordConfig).ToRR(0xc42063cc00, 0xc420093080, 0xc4208f2f00)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/models/dns.go:204 +0xb6f
github.com/StackExchange/dnscontrol/models.(*RecordConfig).Content(0xc42063cc00, 0xc420794bf0, 0x410537)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/models/dns.go:131 +0x7a
github.com/StackExchange/dnscontrol/providers/diff.(*differ).content(0xc4204017c0, 0xc42063cc00, 0xc4200f3b90, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/diff/diff.go:40 +0x43
github.com/StackExchange/dnscontrol/providers/diff.(*differ).IncrementalDiff(0xc4204017c0, 0xc4200c1980, 0xb, 0xb, 0x1266960, 0xc4204017c0, 0x0, 0x0, 0xcedd00, 0xc42008a068, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/diff/diff.go:106 +0xdd1
github.com/StackExchange/dnscontrol/providers/digitalocean.(*DoApi).GetDomainCorrections(0xc420088be8, 0xc4200a6850, 0xc420382504, 0xc, 0xc4200a0f48, 0x1, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/providers/digitalocean/digitaloceanProvider.go:108 +0x224
github.com/StackExchange/dnscontrol/commands.run(0xd651cb, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd63859, 0xa, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:123 +0x5b3
github.com/StackExchange/dnscontrol/commands.Push(0xd651cb, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd63859, 0xa, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:75 +0x89
github.com/StackExchange/dnscontrol/commands.glob..func4.1(0xc4200a8b00, 0x0, 0xc4200a8b00)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:49 +0x4e
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.HandleAction(0xbd34c0, 0xc420099db0, 0xc4200a8b00, 0xc4200c1600, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.Command.Run(0xd5e091, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd7db7a, 0x2d, 0x0, ...)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli.(*App).Run(0xc4201df6c0, 0xc42008c000, 0x2, 0x2, 0x0, 0x0)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/app.go:255 +0x6f8
github.com/StackExchange/dnscontrol/commands.Run(0xc4200b45a0, 0x57, 0xb1bc52)
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/commands/commands.go:49 +0x18a
main.main()
	/Users/tlimoncelli/src/github.com/StackExchange/dnscontrol/main.go:18 +0x34
```

**Comment by tlimoncelli** [comment]
CC: @Deraen

**Comment by Deraen** [comment]
Problem seems be related to SOA records, I guess Digitalocean changed the API so that domain record listing now returns SOA record. E.g. dnsimple provider seems to just filter the SOA record away, so I guess that should be fine for DO also?
