### ISSUE TITLE
Panic when encountering a LOC record on Cloudflare

### ISSUE THREAD

**Issue by sorcix** [StackExchange/dnscontrol#740]
`dnscontrol` crashes while previewing changes on zone with a LOC record from cloudflare.

```
----- DNS Provider: cloudflare...panic: unparsable record received from cloudflare: Unknown rtype (LOC) when parsing (50 43 32.805 N 2 18 52.026 E ) domain=(example.com)

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/cloudflare.(*cfRecord).nativeToRecord(0xc000191c80, 0xc0005b4090, 0x8, 0xc000245c20)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:583 +0x5f0
github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).getRecordsForDomain(0xc0006aa320, 0xc000592300, 0x20, 0xc0005b4090, 0x8, 0x0, 0x0, 0x21, 0x0, 0x0)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/rest.go:70 +0x148
github.com/StackExchange/dnscontrol/providers/cloudflare.(*CloudflareApi).GetDomainCorrections(0xc0006aa320, 0xc000760dc0, 0xa, 0xc000760d00, 0x1, 0x0, 0x0)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/providers/cloudflare/cloudflareProvider.go:145 +0xbd
github.com/StackExchange/dnscontrol/commands.run(0x12c2d4a, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12c0ac2, 0xa, 0x0, ...)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:135 +0x3cc
github.com/StackExchange/dnscontrol/commands.Preview(...)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:87
github.com/StackExchange/dnscontrol/commands.glob..func6.1(0xc00011c640, 0xb, 0xc)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/commands/previewPush.go:25 +0x96
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2.(*Command).Run(0xc0000ab440, 0xc00011c300, 0x0, 0x0)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2/command.go:164 +0x4e0
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2.(*App).RunContext(0xc000102300, 0x15bc040, 0xc000034108, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2/app.go:306 +0x814
github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2.(*App).Run(...)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/vendor/github.com/urfave/cli/v2/app.go:215
github.com/StackExchange/dnscontrol/commands.Run(0xc000120220, 0x14, 0xc00003a118)
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/commands/commands.go:59 +0x23e
main.main()
        /home/vic/Go/src/github.com/StackExchange/dnscontrol/main.go:18 +0x40
```

**Comment by tlimoncelli** [comment]
LOC records are not currently supported by dnscontrol.  Part of the DNSControl design is to crash when unrecognized record types are seen... better to panic than accidentally delete data.

Some potential workarounds:

1. Don't use LOC records
2. The IGNORE() keyword might skip the record. (I haven't tested this)

DNSControl is an all volunteer project.  If you are interested in adding support for the LOC record, there are step-by-step instructions [in the documentation](https://stackexchange.github.io/dnscontrol/adding-new-rtypes) and everyone would be grateful.  I'd gladly help coach you through the process.
